// AUTO-GENERATED by `claude-rc-ctl wire`. Do not edit by hand.
// Mounts <site>/api.ts for sub-sites wired via the privileged `wire` step (Option B).
// A site's api.ts must export a request handler (default, `handler`, or handle<Site>Api).

import * as s_likes from "./likes/api.ts";
import * as s_tier from "./tier/api.ts";

const SITE_MODULES: Record<string, Record<string, unknown>> = {
  "likes": s_likes as unknown as Record<string, unknown>,
  "tier": s_tier as unknown as Record<string, unknown>,
};

function pickHandler(mod: Record<string, unknown>): ((req: Request) => Response | Promise<Response>) | null {
  const candidates: unknown[] = [
    mod.default,
    (mod as Record<string, unknown>).handler,
    ...Object.keys(mod).filter((k) => /^handle.*api$/i.test(k)).map((k) => mod[k]),
    ...Object.values(mod),
  ];
  for (const c of candidates) if (typeof c === "function") return c as (req: Request) => Response | Promise<Response>;
  return null;
}

export async function handleGeneratedSiteApi(request: Request): Promise<Response | null> {
  const m = new URL(request.url).pathname.match(/^\/([a-z0-9_-]+)\/api(?:\/|$)/);
  if (!m) return null;
  const mod = SITE_MODULES[m[1]];
  if (!mod) return null;
  const h = pickHandler(mod);
  return h ? await h(request) : null;
}

