export const TEAM_DATA = {
  ARG: {
    capital: 'Buenos Aires', population: '46M', continent: 'South America',
    fifaRanking: 1, wcAppearances: 18, bestResult: 'Champions (1978, 1986, 2022)',
    funFact: 'Argentina are the reigning World Champions and have won a record 15 Copa América titles.',
    players: [
      { name: 'Lionel Messi',       pos: 'FW', club: 'Inter Miami',     age: 38 },
      { name: 'Lautaro Martínez',   pos: 'FW', club: 'Inter Milan',     age: 27 },
      { name: 'Enzo Fernández',     pos: 'MF', club: 'Chelsea',         age: 25 },
      { name: 'Alexis Mac Allister',pos: 'MF', club: 'Liverpool',       age: 26 },
      { name: 'Rodrigo De Paul',    pos: 'MF', club: 'Atlético Madrid', age: 31 },
      { name: 'Emiliano Martínez',  pos: 'GK', club: 'Aston Villa',     age: 33 },
    ],
  },
  BRA: {
    capital: 'Brasília', population: '215M', continent: 'South America',
    fifaRanking: 5, wcAppearances: 22, bestResult: 'Champions (1958, 1962, 1970, 1994, 2002)',
    funFact: 'Brazil is the only nation to have played in every World Cup and the most successful with 5 titles.',
    players: [
      { name: 'Vinicius Jr.',   pos: 'FW', club: 'Real Madrid',  age: 25 },
      { name: 'Rodrygo',        pos: 'FW', club: 'Real Madrid',  age: 24 },
      { name: 'Endrick',        pos: 'FW', club: 'Real Madrid',  age: 19 },
      { name: 'Raphinha',       pos: 'MF', club: 'Barcelona',    age: 29 },
      { name: 'Casemiro',       pos: 'MF', club: 'Man United',   age: 34 },
      { name: 'Alisson Becker', pos: 'GK', club: 'Liverpool',    age: 33 },
    ],
  },
  FRA: {
    capital: 'Paris', population: '68M', continent: 'Europe',
    fifaRanking: 2, wcAppearances: 16, bestResult: 'Champions (1998, 2018)',
    funFact: 'France\'s "Les Bleus" boast one of the most talented generations in football history.',
    players: [
      { name: 'Kylian Mbappé',    pos: 'FW', club: 'Real Madrid',    age: 27 },
      { name: 'Antoine Griezmann',pos: 'FW', club: 'Atlético Madrid',age: 35 },
      { name: 'Marcus Thuram',    pos: 'FW', club: 'Inter Milan',     age: 28 },
      { name: 'Eduardo Camavinga',pos: 'MF', club: 'Real Madrid',    age: 23 },
      { name: 'Aurélien Tchouaméni',pos:'MF',club: 'Real Madrid',    age: 26 },
      { name: 'Mike Maignan',     pos: 'GK', club: 'AC Milan',       age: 30 },
    ],
  },
  ENG: {
    capital: 'London', population: '57M', continent: 'Europe',
    fifaRanking: 5, wcAppearances: 17, bestResult: 'Champions (1966)',
    funFact: 'England invented the modern game of football and hosted the first Atlanta Soccer News World Cup in Europe in 1966.',
    players: [
      { name: 'Jude Bellingham', pos: 'MF', club: 'Real Madrid',  age: 22 },
      { name: 'Bukayo Saka',     pos: 'FW', club: 'Arsenal',      age: 24 },
      { name: 'Harry Kane',      pos: 'FW', club: 'Bayern Munich',age: 32 },
      { name: 'Declan Rice',     pos: 'MF', club: 'Arsenal',      age: 27 },
      { name: 'Phil Foden',      pos: 'MF', club: 'Man City',     age: 26 },
      { name: 'Jordan Pickford', pos: 'GK', club: 'Everton',      age: 32 },
    ],
  },
  ESP: {
    capital: 'Madrid', population: '47M', continent: 'Europe',
    fifaRanking: 3, wcAppearances: 16, bestResult: 'Champions (2010)',
    funFact: 'Spain\'s tiki-taka style revolutionized modern football, winning three consecutive major tournaments 2008-2012.',
    players: [
      { name: 'Lamine Yamal',  pos: 'FW', club: 'Barcelona',    age: 18 },
      { name: 'Pedri',         pos: 'MF', club: 'Barcelona',    age: 23 },
      { name: 'Dani Olmo',     pos: 'MF', club: 'Barcelona',    age: 27 },
      { name: 'Álvaro Morata', pos: 'FW', club: 'AC Milan',     age: 33 },
      { name: 'Rodri',         pos: 'MF', club: 'Man City',     age: 29 },
      { name: 'Unai Simón',    pos: 'GK', club: 'Athletic Club',age: 28 },
    ],
  },
  GER: {
    capital: 'Berlin', population: '84M', continent: 'Europe',
    fifaRanking: 13, wcAppearances: 20, bestResult: 'Champions (1954, 1974, 1990, 2014)',
    funFact: 'Germany hosted the 2006 World Cup "Summer Fairy Tale" and are the most successful European nation with 4 titles.',
    players: [
      { name: 'Florian Wirtz',  pos: 'MF', club: 'Bayer Leverkusen', age: 22 },
      { name: 'Jamal Musiala',  pos: 'MF', club: 'Bayern Munich',    age: 22 },
      { name: 'Kai Havertz',    pos: 'FW', club: 'Arsenal',          age: 26 },
      { name: 'Leroy Sané',     pos: 'FW', club: 'Bayern Munich',    age: 30 },
      { name: 'Leon Goretzka',  pos: 'MF', club: 'Bayern Munich',    age: 31 },
      { name: 'Manuel Neuer',   pos: 'GK', club: 'Bayern Munich',    age: 40 },
    ],
  },
  POR: {
    capital: 'Lisbon', population: '10M', continent: 'Europe',
    fifaRanking: 6, wcAppearances: 9, bestResult: '3rd Place (1966)',
    funFact: 'Portugal\'s "Golden Generation" won Euro 2016 and the inaugural UEFA Nations League in 2019.',
    players: [
      { name: 'Cristiano Ronaldo',  pos: 'FW', club: 'Al Nassr',   age: 41 },
      { name: 'Bruno Fernandes',    pos: 'MF', club: 'Man United',  age: 31 },
      { name: 'Rafael Leão',        pos: 'FW', club: 'AC Milan',    age: 26 },
      { name: 'Vitinha',            pos: 'MF', club: 'PSG',         age: 26 },
      { name: 'Bernardo Silva',     pos: 'MF', club: 'Man City',    age: 31 },
      { name: 'Diogo Costa',        pos: 'GK', club: 'Porto',       age: 25 },
    ],
  },
  NED: {
    capital: 'Amsterdam', population: '17M', continent: 'Europe',
    fifaRanking: 7, wcAppearances: 11, bestResult: 'Runners-up (1974, 1978, 2010)',
    funFact: 'The Netherlands invented "Total Football" in the 1970s, revolutionizing the game with players like Johan Cruyff.',
    players: [
      { name: 'Virgil van Dijk', pos: 'DF', club: 'Liverpool',      age: 34 },
      { name: 'Cody Gakpo',      pos: 'FW', club: 'Liverpool',      age: 26 },
      { name: 'Frenkie de Jong', pos: 'MF', club: 'Barcelona',      age: 29 },
      { name: 'Memphis Depay',   pos: 'FW', club: 'Atlético Madrid',age: 32 },
      { name: 'Tijjani Reijnders',pos:'MF', club: 'AC Milan',       age: 26 },
      { name: 'Mark Flekken',    pos: 'GK', club: 'Brentford',      age: 31 },
    ],
  },
  ITA: {
    capital: 'Rome', population: '60M', continent: 'Europe',
    fifaRanking: 9, wcAppearances: 18, bestResult: 'Champions (1934, 1938, 1982, 2006)',
    funFact: 'Italy is one of only two nations to win the World Cup as host, and won back-to-back titles in 1934 and 1938.',
    players: [
      { name: 'Gianluigi Donnarumma', pos: 'GK', club: 'PSG',            age: 26 },
      { name: 'Nicolò Barella',       pos: 'MF', club: 'Inter Milan',     age: 27 },
      { name: 'Sandro Tonali',        pos: 'MF', club: 'Newcastle',       age: 24 },
      { name: 'Federico Chiesa',      pos: 'FW', club: 'Liverpool',       age: 28 },
      { name: 'Giacomo Raspadori',    pos: 'FW', club: 'Napoli',          age: 25 },
      { name: 'Alessandro Bastoni',   pos: 'DF', club: 'Inter Milan',     age: 26 },
    ],
  },
  BEL: {
    capital: 'Brussels', population: '11M', continent: 'Europe',
    fifaRanking: 10, wcAppearances: 13, bestResult: '3rd Place (2018)',
    funFact: 'Belgium\'s "Golden Generation" reached their highest-ever Atlanta Soccer News ranking of #1 in 2018.',
    players: [
      { name: 'Kevin De Bruyne', pos: 'MF', club: 'Man City',     age: 35 },
      { name: 'Romelu Lukaku',   pos: 'FW', club: 'Napoli',       age: 32 },
      { name: 'Thibaut Courtois',pos: 'GK', club: 'Real Madrid',  age: 34 },
      { name: 'Jeremy Doku',     pos: 'FW', club: 'Man City',     age: 23 },
      { name: 'Amadou Onana',    pos: 'MF', club: 'Aston Villa',  age: 23 },
      { name: 'Wout Faes',       pos: 'DF', club: 'Leicester',    age: 27 },
    ],
  },
  CRO: {
    capital: 'Zagreb', population: '4M', continent: 'Europe',
    fifaRanking: 11, wcAppearances: 7, bestResult: 'Runners-up (2018)',
    funFact: 'Croatia reached back-to-back World Cup semi-finals (2018, 2022) making them one of the most consistent small nations.',
    players: [
      { name: 'Luka Modrić',   pos: 'MF', club: 'Real Madrid',     age: 41 },
      { name: 'Mateo Kovačić', pos: 'MF', club: 'Man City',        age: 32 },
      { name: 'Joško Gvardiol',pos: 'DF', club: 'Man City',        age: 23 },
      { name: 'Nikola Vlašić', pos: 'MF', club: 'West Ham',        age: 28 },
      { name: 'Andrej Kramarić',pos:'FW', club: 'Hoffenheim',      age: 34 },
      { name: 'Dominik Livaković',pos:'GK',club: 'Fenerbahçe',    age: 29 },
    ],
  },
  SUI: {
    capital: 'Bern', population: '8.7M', continent: 'Europe',
    fifaRanking: 20, wcAppearances: 12, bestResult: 'Quarter-finals (1934, 1938, 1954)',
    funFact: 'Switzerland co-hosted the 1954 World Cup and has been a consistent qualifier for major tournaments.',
    players: [
      { name: 'Granit Xhaka',  pos: 'MF', club: 'Bayer Leverkusen', age: 33 },
      { name: 'Xherdan Shaqiri',pos: 'FW', club: 'Chicago Fire',    age: 34 },
      { name: 'Breel Embolo',  pos: 'FW', club: 'Monaco',           age: 29 },
      { name: 'Remo Freuler',  pos: 'MF', club: 'Bologna',          age: 32 },
      { name: 'Silvan Widmer', pos: 'DF', club: 'Mainz',            age: 31 },
      { name: 'Yann Sommer',   pos: 'GK', club: 'Inter Milan',      age: 37 },
    ],
  },
  DEN: {
    capital: 'Copenhagen', population: '5.9M', continent: 'Europe',
    fifaRanking: 23, wcAppearances: 5, bestResult: 'Quarter-finals (1998)',
    funFact: 'Denmark won Euro 1992 despite not qualifying — they were called up as a late replacement for Yugoslavia.',
    players: [
      { name: 'Christian Eriksen', pos: 'MF', club: 'Man United',    age: 34 },
      { name: 'Pierre-Emile Højbjerg', pos: 'MF', club: 'Marseille', age: 30 },
      { name: 'Rasmus Højlund',   pos: 'FW', club: 'Man United',     age: 23 },
      { name: 'Joakim Mæhle',     pos: 'DF', club: 'Atalanta',       age: 28 },
      { name: 'Andreas Skov Olsen',pos:'FW', club: 'Club Brugge',    age: 25 },
      { name: 'Kasper Schmeichel', pos: 'GK', club: 'Anderlecht',    age: 39 },
    ],
  },
  AUT: {
    capital: 'Vienna', population: '9M', continent: 'Europe',
    fifaRanking: 25, wcAppearances: 7, bestResult: '3rd Place (1954)',
    funFact: 'Austria hosted and reached the semi-finals of the 1934 World Cup with their legendary "Wunderteam".',
    players: [
      { name: 'David Alaba',      pos: 'DF', club: 'Real Madrid',    age: 33 },
      { name: 'Marcel Sabitzer',  pos: 'MF', club: 'Dortmund',      age: 31 },
      { name: 'Marko Arnautovic', pos: 'FW', club: 'Man United',    age: 37 },
      { name: 'Florian Grillitsch',pos:'MF', club: 'Ajax',          age: 30 },
      { name: 'Konrad Laimer',    pos: 'MF', club: 'Bayern Munich', age: 27 },
      { name: 'Patrick Pentz',    pos: 'GK', club: 'Bayer Leverkusen',age: 27 },
    ],
  },
  SRB: {
    capital: 'Belgrade', population: '7M', continent: 'Europe',
    fifaRanking: 29, wcAppearances: 13, bestResult: '4th Place (1930, 1962) as Yugoslavia',
    funFact: 'Serbia (as Yugoslavia) was one of four teams at the very first World Cup in 1930.',
    players: [
      { name: 'Aleksandar Mitrović', pos: 'FW', club: 'Al Hilal',     age: 31 },
      { name: 'Luka Jović',          pos: 'FW', club: 'AC Milan',      age: 28 },
      { name: 'Filip Kostić',        pos: 'MF', club: 'Juventus',      age: 32 },
      { name: 'Dušan Tadić',         pos: 'FW', club: 'Fenerbahçe',   age: 37 },
      { name: 'Sergej Milinković-Savić', pos: 'MF', club: 'Al Hilal', age: 30 },
      { name: 'Predrag Rajković',    pos: 'GK', club: 'Mallorca',      age: 29 },
    ],
  },
  POL: {
    capital: 'Warsaw', population: '38M', continent: 'Europe',
    fifaRanking: 28, wcAppearances: 9, bestResult: '3rd Place (1974, 1982)',
    funFact: 'Robert Lewandowski became the first Polish player to win the Atlanta Soccer News Best Men\'s Player award in 2020.',
    players: [
      { name: 'Robert Lewandowski', pos: 'FW', club: 'Barcelona',     age: 37 },
      { name: 'Piotr Zieliński',    pos: 'MF', club: 'Inter Milan',   age: 32 },
      { name: 'Sebastian Szymański',pos: 'MF', club: 'Fenerbahçe',   age: 29 },
      { name: 'Matty Cash',         pos: 'DF', club: 'Aston Villa',   age: 28 },
      { name: 'Nicola Zalewski',    pos: 'MF', club: 'Roma',          age: 24 },
      { name: 'Wojciech Szczęsny',  pos: 'GK', club: 'Barcelona',    age: 36 },
    ],
  },
  TUR: {
    capital: 'Ankara', population: '85M', continent: 'Europe/Asia',
    fifaRanking: 26, wcAppearances: 2, bestResult: '3rd Place (2002)',
    funFact: 'Turkey finished 3rd on their World Cup debut in 2002, with Hakan Şükür scoring the fastest-ever WC goal in 11 seconds.',
    players: [
      { name: 'Hakan Çalhanoğlu', pos: 'MF', club: 'Inter Milan',     age: 32 },
      { name: 'Arda Güler',       pos: 'MF', club: 'Real Madrid',     age: 20 },
      { name: 'Kerem Aktürkoğlu', pos: 'FW', club: 'Galatasaray',    age: 26 },
      { name: 'Merih Demiral',    pos: 'DF', club: 'Al Ahli',         age: 27 },
      { name: 'Yusuf Yazıcı',     pos: 'MF', club: 'LOSC Lille',      age: 28 },
      { name: 'Altay Bayındır',   pos: 'GK', club: 'Man United',      age: 27 },
    ],
  },
  SCO: {
    capital: 'Edinburgh', population: '5.5M', continent: 'Europe',
    fifaRanking: 38, wcAppearances: 8, bestResult: 'Group Stage',
    funFact: 'Scotland played in the first-ever international football match against England in 1872, drawing 0-0.',
    players: [
      { name: 'Andy Robertson',  pos: 'DF', club: 'Liverpool',      age: 32 },
      { name: 'Scott McTominay', pos: 'MF', club: 'Napoli',         age: 29 },
      { name: 'Che Adams',       pos: 'FW', club: 'Torino',         age: 29 },
      { name: 'Ryan Christie',   pos: 'MF', club: 'Bournemouth',    age: 30 },
      { name: 'Callum McGregor', pos: 'MF', club: 'Celtic',         age: 31 },
      { name: 'Angus Gunn',      pos: 'GK', club: 'Norwich',        age: 29 },
    ],
  },
  MAR: {
    capital: 'Rabat', population: '37M', continent: 'Africa',
    fifaRanking: 14, wcAppearances: 6, bestResult: 'Semi-finals (2022)',
    funFact: 'Morocco became the first African nation to reach a World Cup semi-final at Qatar 2022.',
    players: [
      { name: 'Hakim Ziyech',   pos: 'FW', club: 'Galatasaray',  age: 33 },
      { name: 'Youssef En-Nesyri', pos: 'FW', club: 'Fenerbahçe', age: 28 },
      { name: 'Achraf Hakimi',  pos: 'DF', club: 'PSG',           age: 27 },
      { name: 'Azzedine Ounahi',pos: 'MF', club: 'Marseille',     age: 25 },
      { name: 'Sofyan Amrabat', pos: 'MF', club: 'Al Batayih',    age: 29 },
      { name: 'Yassine Bounou', pos: 'GK', club: 'Al Hilal',      age: 33 },
    ],
  },
  SEN: {
    capital: 'Dakar', population: '17M', continent: 'Africa',
    fifaRanking: 18, wcAppearances: 3, bestResult: 'Quarter-finals (2002)',
    funFact: 'Senegal won the 2022 Africa Cup of Nations for the first time in their history.',
    players: [
      { name: 'Sadio Mané',       pos: 'FW', club: 'Al Nassr',       age: 34 },
      { name: 'Ismaïla Sarr',     pos: 'FW', club: 'Crystal Palace', age: 26 },
      { name: 'Idrissa Gueye',    pos: 'MF', club: 'Everton',        age: 36 },
      { name: 'Krepin Diatta',    pos: 'FW', club: 'Monaco',         age: 26 },
      { name: 'Kalidou Koulibaly',pos: 'DF', club: 'Al Hilal',       age: 34 },
      { name: 'Édouard Mendy',    pos: 'GK', club: 'Al Ahli',        age: 32 },
    ],
  },
  NGA: {
    capital: 'Abuja', population: '220M', continent: 'Africa',
    fifaRanking: 35, wcAppearances: 7, bestResult: 'Round of 16 (1994, 1998, 2014)',
    funFact: 'Nigeria\'s Super Eagles won Olympic gold at Atlanta 1996, beating Argentina in the semi-final.',
    players: [
      { name: 'Victor Osimhen', pos: 'FW', club: 'Galatasaray',   age: 27 },
      { name: 'Ademola Lookman',pos: 'FW', club: 'Atalanta',      age: 27 },
      { name: 'Alex Iwobi',     pos: 'MF', club: 'Fulham',        age: 30 },
      { name: 'Calvin Bassey',  pos: 'DF', club: 'Fulham',        age: 25 },
      { name: 'Wilfred Ndidi',  pos: 'MF', club: 'Leicester',     age: 29 },
      { name: 'Stanley Nwabali',pos: 'GK', club: 'Chippa United', age: 28 },
    ],
  },
  EGY: {
    capital: 'Cairo', population: '105M', continent: 'Africa',
    fifaRanking: 37, wcAppearances: 4, bestResult: 'Group Stage',
    funFact: 'Egypt is Africa\'s most successful nation at the Africa Cup of Nations, having won it a record 7 times.',
    players: [
      { name: 'Mohamed Salah',    pos: 'FW', club: 'Liverpool',       age: 33 },
      { name: 'Omar Marmoush',    pos: 'FW', club: 'Manchester City', age: 26 },
      { name: 'Mostafa Mohamed',  pos: 'FW', club: 'Nantes',         age: 27 },
      { name: 'Tarek Hamed',      pos: 'MF', club: 'Zamalek',        age: 36 },
      { name: 'Amr El Sulaya',    pos: 'MF', club: 'Al Qadsiah',     age: 26 },
      { name: 'Mohamed El-Shenawy',pos:'GK', club: 'Al Ahly',        age: 37 },
    ],
  },
  CIV: {
    capital: 'Yamoussoukro', population: '27M', continent: 'Africa',
    fifaRanking: 45, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Ivory Coast won the 2023 Africa Cup of Nations on home soil, defeating Nigeria in the final.',
    players: [
      { name: 'Sébastien Haller',  pos: 'FW', club: 'Dortmund',      age: 31 },
      { name: 'Wilfried Zaha',     pos: 'FW', club: 'Galatasaray',   age: 33 },
      { name: 'Franck Kessié',     pos: 'MF', club: 'Al Ahli',       age: 29 },
      { name: 'Ibrahim Sangaré',   pos: 'MF', club: 'Nottm Forest',  age: 27 },
      { name: 'Serge Aurier',      pos: 'DF', club: 'Villarreal',    age: 33 },
      { name: 'Yahia Fofana',      pos: 'GK', club: 'Chelsea',       age: 28 },
    ],
  },
  CMR: {
    capital: 'Yaoundé', population: '28M', continent: 'Africa',
    fifaRanking: 43, wcAppearances: 8, bestResult: 'Quarter-finals (1990)',
    funFact: 'Cameroon\'s Roger Milla became a World Cup legend at Italia 1990, famously celebrating goals with a hip-shake dance.',
    players: [
      { name: 'André-Frank Zambo Anguissa', pos: 'MF', club: 'Napoli',    age: 29 },
      { name: 'Vincent Aboubakar',          pos: 'FW', club: 'Al Qadsiah',age: 33 },
      { name: 'Martin Hongla',              pos: 'MF', club: 'Verona',     age: 27 },
      { name: 'Harold Moukoudi',            pos: 'DF', club: 'Charlotte FC',age: 28 },
      { name: 'Clinton Njie',               pos: 'FW', club: 'Gençlerbirliği',age: 31 },
      { name: 'André Onana',                pos: 'GK', club: 'Man United', age: 29 },
    ],
  },
  GHA: {
    capital: 'Accra', population: '33M', continent: 'Africa',
    fifaRanking: 60, wcAppearances: 4, bestResult: 'Quarter-finals (2010)',
    funFact: 'Ghana\'s Black Stars were one penalty away from becoming the first African team to reach a World Cup semi-final in 2010.',
    players: [
      { name: 'Thomas Partey',    pos: 'MF', club: 'Arsenal',         age: 32 },
      { name: 'Mohammed Kudus',   pos: 'FW', club: 'West Ham',        age: 24 },
      { name: 'Jordan Ayew',      pos: 'FW', club: 'Leicester',       age: 33 },
      { name: 'Tariq Lamptey',    pos: 'DF', club: 'Brighton',        age: 24 },
      { name: 'Ernest Nuamah',    pos: 'FW', club: 'Olympique Lyon',  age: 21 },
      { name: 'Lawrence Ati Zigi',pos: 'GK', club: 'St. Gallen',     age: 28 },
    ],
  },
  TUN: {
    capital: 'Tunis', population: '12M', continent: 'Africa',
    fifaRanking: 31, wcAppearances: 6, bestResult: 'Group Stage',
    funFact: 'Tunisia was the first African team to win a World Cup match, beating Mexico 3-1 in 1978.',
    players: [
      { name: 'Youssef Msakni',   pos: 'FW', club: 'Al Arabi',       age: 34 },
      { name: 'Aïssa Laïdouni',   pos: 'MF', club: 'Union Berlin',   age: 28 },
      { name: 'Wahbi Khazri',     pos: 'FW', club: 'Montpellier',    age: 33 },
      { name: 'Dylan Bronn',      pos: 'DF', club: 'Salernitana',    age: 28 },
      { name: 'Hannibal Mejbri',  pos: 'MF', club: 'Burnley',        age: 22 },
      { name: 'Aymen Dahmen',     pos: 'GK', club: 'Montpellier',    age: 27 },
    ],
  },
  RSA: {
    capital: 'Pretoria', population: '60M', continent: 'Africa',
    fifaRanking: 68, wcAppearances: 3, bestResult: 'Group Stage (2010 host)',
    funFact: 'South Africa hosted the first-ever World Cup on African soil in 2010, popularizing the vuvuzela worldwide.',
    players: [
      { name: 'Percy Tau',        pos: 'FW', club: 'Al Ahly',        age: 31 },
      { name: 'Themba Zwane',     pos: 'MF', club: 'Mamelodi Sundowns',age:35 },
      { name: 'Evidence Makgopa', pos: 'FW', club: 'Bafana',         age: 25 },
      { name: 'Ronwen Williams',  pos: 'GK', club: 'Mamelodi Sundowns',age:32 },
      { name: 'Siyanda Xulu',     pos: 'DF', club: 'Shakhtar',       age: 31 },
      { name: 'Yusuf Maart',      pos: 'MF', club: 'Kaizer Chiefs',  age: 28 },
    ],
  },
  JPN: {
    capital: 'Tokyo', population: '125M', continent: 'Asia',
    fifaRanking: 17, wcAppearances: 8, bestResult: 'Round of 16 (2002, 2010, 2018, 2022)',
    funFact: 'Japan co-hosted the 2002 World Cup with South Korea, becoming the first Asian nation to host the tournament.',
    players: [
      { name: 'Kaoru Mitoma',  pos: 'FW', club: 'Brighton',       age: 27 },
      { name: 'Takefusa Kubo', pos: 'FW', club: 'Real Sociedad',  age: 24 },
      { name: 'Daichi Kamada', pos: 'MF', club: 'Crystal Palace', age: 28 },
      { name: 'Ritsu Doan',    pos: 'FW', club: 'Freiburg',       age: 27 },
      { name: 'Wataru Endo',   pos: 'MF', club: 'Liverpool',      age: 31 },
      { name: 'Shuichi Gonda', pos: 'GK', club: 'Shimizu S-Pulse',age: 35 },
    ],
  },
  KOR: {
    capital: 'Seoul', population: '52M', continent: 'Asia',
    fifaRanking: 22, wcAppearances: 11, bestResult: '4th Place (2002)',
    funFact: 'South Korea became the first Asian nation to reach a World Cup semi-final as co-hosts in 2002.',
    players: [
      { name: 'Son Heung-min',    pos: 'FW', club: 'Tottenham',     age: 34 },
      { name: 'Lee Kang-in',      pos: 'FW', club: 'PSG',           age: 24 },
      { name: 'Hwang Hee-chan',    pos: 'FW', club: 'Wolves',        age: 29 },
      { name: 'Kim Min-jae',       pos: 'DF', club: 'Bayern Munich', age: 28 },
      { name: 'Hwang In-beom',    pos: 'MF', club: 'Vancouver',     age: 29 },
      { name: 'Kim Seung-gyu',     pos: 'GK', club: 'Vissel Kobe',  age: 35 },
    ],
  },
  AUS: {
    capital: 'Canberra', population: '26M', continent: 'Oceania/Asia',
    fifaRanking: 25, wcAppearances: 6, bestResult: 'Round of 16 (2006, 2022)',
    funFact: 'Australia switched from the Oceania confederation to Asia in 2006, significantly boosting their WC qualification chances.',
    players: [
      { name: 'Mathew Leckie',   pos: 'FW', club: 'Melbourne City', age: 34 },
      { name: 'Ajdin Hrustic',   pos: 'MF', club: 'Hellas Verona', age: 29 },
      { name: 'Garang Kuol',     pos: 'FW', club: 'Hearts',        age: 22 },
      { name: 'Aaron Mooy',      pos: 'MF', club: 'Celtic',        age: 35 },
      { name: 'Harry Souttar',   pos: 'DF', club: 'Leicester',     age: 26 },
      { name: 'Mathew Ryan',     pos: 'GK', club: 'Real Sociedad', age: 33 },
    ],
  },
  IRN: {
    capital: 'Tehran', population: '87M', continent: 'Asia',
    fifaRanking: 22, wcAppearances: 6, bestResult: 'Group Stage',
    funFact: 'Iran\'s 1978 squad included players from the Shah\'s era. Their 2022 team stood defiantly silent during the anthem in solidarity with protesters.',
    players: [
      { name: 'Sardar Azmoun',   pos: 'FW', club: 'Bayer Leverkusen', age: 30 },
      { name: 'Mehdi Taremi',    pos: 'FW', club: 'Inter Milan',      age: 32 },
      { name: 'Ali Gholizadeh', pos: 'FW', club: 'Sharjah',          age: 29 },
      { name: 'Saman Ghoddos',  pos: 'MF', club: 'Brentford',        age: 31 },
      { name: 'Milad Mohammadi',pos: 'DF', club: 'AEK Athens',       age: 30 },
      { name: 'Alireza Beiranvand',pos:'GK',club: 'Persepolis',      age: 32 },
    ],
  },
  KSA: {
    capital: 'Riyadh', population: '35M', continent: 'Asia',
    fifaRanking: 55, wcAppearances: 6, bestResult: 'Round of 16 (1994)',
    funFact: 'Saudi Arabia pulled off one of the biggest World Cup upsets ever, beating Argentina 2-1 at Qatar 2022.',
    players: [
      { name: 'Salem Al-Dawsari', pos: 'FW', club: 'Al Hilal',      age: 33 },
      { name: 'Firas Al-Buraikan',pos: 'FW', club: 'Al Fateh',      age: 25 },
      { name: 'Mohammed Al-Owais',pos: 'GK', club: 'Al Hilal',      age: 33 },
      { name: 'Saleh Al-Shehri', pos: 'FW', club: 'Al Hilal',       age: 32 },
      { name: 'Ali Al-Hassan',   pos: 'MF', club: 'Al Shabab',      age: 26 },
      { name: 'Ali Al-Bulaihi',  pos: 'DF', club: 'Al Hilal',       age: 33 },
    ],
  },
  IRQ: {
    capital: 'Baghdad', population: '42M', continent: 'Asia',
    fifaRanking: 70, wcAppearances: 1, bestResult: 'Group Stage (1986)',
    funFact: 'Iraq won the AFC Asian Cup in 2007, their first and only continental title, defeating Saudi Arabia in the final.',
    players: [
      { name: 'Mohanad Ali',     pos: 'FW', club: 'Al Zawraa',      age: 27 },
      { name: 'Aymen Hussein',   pos: 'FW', club: 'Al Shorta',      age: 28 },
      { name: 'Amjad Attwan',    pos: 'MF', club: 'Al Shorta',      age: 29 },
      { name: 'Ali Faez',        pos: 'MF', club: 'Duhok SC',       age: 26 },
      { name: 'Rebin Sulaka',    pos: 'DF', club: 'Al Zawraa',      age: 28 },
      { name: 'Jalal Hassan',    pos: 'GK', club: 'Al Zawraa',      age: 31 },
    ],
  },
  QAT: {
    capital: 'Doha', population: '2.9M', continent: 'Asia',
    fifaRanking: 58, wcAppearances: 2, bestResult: 'Group Stage (2022 host)',
    funFact: 'Qatar hosted the 2022 World Cup, the first in the Middle East, and became the first host nation to be eliminated in the group stage.',
    players: [
      { name: 'Akram Afif',      pos: 'FW', club: 'Al Sadd',        age: 28 },
      { name: 'Almoez Ali',      pos: 'FW', club: 'Al Duhail',      age: 28 },
      { name: 'Hassan Al-Haydos',pos: 'MF', club: 'Al Sadd',        age: 34 },
      { name: 'Assim Madibo',    pos: 'MF', club: 'Al Sadd',        age: 27 },
      { name: 'Bassam Al-Rawi',  pos: 'DF', club: 'Al Sadd',        age: 29 },
      { name: 'Meshaal Barsham', pos: 'GK', club: 'Al Sadd',        age: 28 },
    ],
  },
  USA: {
    capital: 'Washington D.C.', population: '335M', continent: 'North America',
    fifaRanking: 16, wcAppearances: 11, bestResult: '3rd Place (1930)',
    funFact: 'The USA co-hosts 2026 alongside Canada and Mexico, aiming to improve on their best result since 1930.',
    players: [
      { name: 'Christian Pulisic',pos: 'FW', club: 'AC Milan',       age: 27 },
      { name: 'Giovanni Reyna',   pos: 'MF', club: 'Dortmund',       age: 23 },
      { name: 'Weston McKennie', pos: 'MF', club: 'Leeds',           age: 27 },
      { name: 'Tim Weah',         pos: 'FW', club: 'Juventus',       age: 25 },
      { name: 'Yunus Musah',      pos: 'MF', club: 'AC Milan',       age: 23 },
      { name: 'Matt Turner',      pos: 'GK', club: 'Crystal Palace', age: 30 },
    ],
  },
  MEX: {
    capital: 'Mexico City', population: '130M', continent: 'North America',
    fifaRanking: 15, wcAppearances: 17, bestResult: 'Quarter-finals (1970, 1986)',
    funFact: 'Mexico has famously reached the Round of 16 in seven consecutive World Cups (1994-2018), known as the "Quinto Partido" curse.',
    players: [
      { name: 'Hirving Lozano',  pos: 'FW', club: 'PSV Eindhoven',  age: 30 },
      { name: 'Raúl Jiménez',    pos: 'FW', club: 'Fulham',         age: 34 },
      { name: 'Santiago Giménez',pos: 'FW', club: 'AC Milan',       age: 24 },
      { name: 'Edson Álvarez',   pos: 'MF', club: 'West Ham',       age: 27 },
      { name: 'Chucky Lozano',   pos: 'FW', club: 'PSV',            age: 30 },
      { name: 'Guillermo Ochoa', pos: 'GK', club: 'América',        age: 40 },
    ],
  },
  CAN: {
    capital: 'Ottawa', population: '38M', continent: 'North America',
    fifaRanking: 44, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Canada qualified for the 2022 World Cup for the first time since 1986, led by Alphonso Davies and Jonathan David.',
    players: [
      { name: 'Alphonso Davies',  pos: 'DF', club: 'Bayern Munich',  age: 25 },
      { name: 'Jonathan David',   pos: 'FW', club: 'LOSC Lille',     age: 25 },
      { name: 'Tajon Buchanan',   pos: 'FW', club: 'Inter Milan',    age: 26 },
      { name: 'Stephen Eustáquio',pos: 'MF', club: 'Porto',          age: 27 },
      { name: 'Ismaël Koné',      pos: 'MF', club: 'Watford',        age: 23 },
      { name: 'Maxime Crépeau',   pos: 'GK', club: 'LA Galaxy',      age: 30 },
    ],
  },
  CRC: {
    capital: 'San José', population: '5.2M', continent: 'North America',
    fifaRanking: 53, wcAppearances: 6, bestResult: 'Quarter-finals (2014)',
    funFact: 'Costa Rica\'s remarkable quarter-final run at Brazil 2014 included eliminating Uruguay and Italy in the group stage.',
    players: [
      { name: 'Keylor Navas',   pos: 'GK', club: 'Newell\'s Old Boys',age: 39 },
      { name: 'Bryan Ruiz',     pos: 'MF', club: 'Retired',          age: 39 },
      { name: 'Joel Campbell',  pos: 'FW', club: 'León',             age: 33 },
      { name: 'Yeltsin Tejeda', pos: 'MF', club: 'CD Saprissa',     age: 32 },
      { name: 'Francisco Calvo',pos: 'DF', club: 'Konyaspor',       age: 31 },
      { name: 'Aarón Suárez',   pos: 'GK', club: 'CD Saprissa',    age: 27 },
    ],
  },
  PAN: {
    capital: 'Panama City', population: '4.3M', continent: 'North America',
    fifaRanking: 72, wcAppearances: 2, bestResult: 'Group Stage (2018)',
    funFact: 'Panama qualified for their first-ever World Cup in 2018, with the entire nation celebrating in the streets.',
    players: [
      { name: 'Ismael Díaz',     pos: 'FW', club: 'Porto',           age: 25 },
      { name: 'Cecilio Waterman',pos: 'FW', club: 'Konyaspor',       age: 34 },
      { name: 'Adalberto Carrasquilla',pos:'MF',club:'Al-Qadisiyah', age: 25 },
      { name: 'Anibal Godoy',    pos: 'MF', club: 'San Jose EQ',     age: 37 },
      { name: 'Eric Davis',      pos: 'DF', club: 'CD Lugo',         age: 36 },
      { name: 'Luis Mejía',      pos: 'GK', club: 'Montpellier',    age: 26 },
    ],
  },
  HON: {
    capital: 'Tegucigalpa', population: '10M', continent: 'North America',
    fifaRanking: 85, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Honduras appeared at three consecutive World Cups (1982, 2010, 2014) despite never qualifying before or since.',
    players: [
      { name: 'Alberth Elis',    pos: 'FW', club: 'Montpellier',    age: 28 },
      { name: 'Romell Quioto',   pos: 'FW', club: 'CF Montréal',    age: 33 },
      { name: 'Bryan Acosta',    pos: 'MF', club: 'FC Dallas',       age: 31 },
      { name: 'Kervin Arriaga',  pos: 'MF', club: 'Santos Laguna',  age: 24 },
      { name: 'Marcelo Santos',  pos: 'DF', club: 'Marathon',        age: 25 },
      { name: 'Harold Fonseca',  pos: 'GK', club: 'Olimpia',        age: 27 },
    ],
  },
  SLV: {
    capital: 'San Salvador', population: '6.5M', continent: 'North America',
    fifaRanking: 78, wcAppearances: 2, bestResult: 'Group Stage (1970, 1982)',
    funFact: 'El Salvador qualified in 1970 after winning the "Football War" qualifier against Honduras, which sparked a real 100-hour military conflict.',
    players: [
      { name: 'Nelson Bonilla',   pos: 'FW', club: 'ATL Alashkert',  age: 32 },
      { name: 'Enrico Dueñas',   pos: 'FW', club: 'Al Taqdom',      age: 23 },
      { name: 'Darwin Cerén',    pos: 'MF', club: 'Philadelphia Union',age:32},
      { name: 'Joshua Pérez',    pos: 'MF', club: 'Rayo Vallecano', age: 23 },
      { name: 'Roberto Domínguez',pos:'DF', club: 'CD FAS',          age: 27 },
      { name: 'Mario González',  pos: 'GK', club: 'Alianza FC',     age: 27 },
    ],
  },
  JAM: {
    capital: 'Kingston', population: '2.9M', continent: 'North America',
    fifaRanking: 47, wcAppearances: 1, bestResult: 'Group Stage (1998)',
    funFact: 'Jamaica\'s "Reggae Boyz" made their World Cup debut in France 1998 and became cult heroes, starring in a feature film.',
    players: [
      { name: 'Michail Antonio',pos: 'FW', club: 'Nottm Forest',   age: 35 },
      { name: 'Bobby Reid',     pos: 'FW', club: 'Fulham',         age: 31 },
      { name: 'Demarai Gray',   pos: 'FW', club: 'Fulham',         age: 29 },
      { name: 'Andre Blake',    pos: 'GK', club: 'Philadelphia',   age: 33 },
      { name: 'Oniel Fisher',   pos: 'DF', club: 'DC United',      age: 30 },
      { name: 'Ethan Pinnock',  pos: 'DF', club: 'Brentford',      age: 31 },
    ],
  },
  COL: {
    capital: 'Bogotá', population: '52M', continent: 'South America',
    fifaRanking: 12, wcAppearances: 6, bestResult: 'Quarter-finals (2014)',
    funFact: 'Colombia\'s James Rodríguez won the Golden Boot at the 2014 World Cup and his team reached the quarter-finals for the first time.',
    players: [
      { name: 'Luis Díaz',       pos: 'FW', club: 'Liverpool',       age: 28 },
      { name: 'James Rodríguez', pos: 'MF', club: 'Rayo Vallecano', age: 33 },
      { name: 'Jhon Córdoba',    pos: 'FW', club: 'Krasnodar',       age: 31 },
      { name: 'Richard Ríos',    pos: 'MF', club: 'Palmeiras',       age: 25 },
      { name: 'Dávinson Sánchez',pos: 'DF', club: 'Galatasaray',    age: 28 },
      { name: 'Camilo Vargas',   pos: 'GK', club: 'Atlas FC',        age: 32 },
    ],
  },
  ECU: {
    capital: 'Quito', population: '18M', continent: 'South America',
    fifaRanking: 33, wcAppearances: 4, bestResult: 'Round of 16 (2006)',
    funFact: 'Ecuador opened the 2022 World Cup with a 2-0 win over host Qatar, with Enner Valencia scoring both goals.',
    players: [
      { name: 'Moisés Caicedo',  pos: 'MF', club: 'Chelsea',         age: 23 },
      { name: 'Enner Valencia',  pos: 'FW', club: 'Internacional',   age: 35 },
      { name: 'Piero Hincapié',  pos: 'DF', club: 'Bayer Leverkusen',age: 23 },
      { name: 'Gonzalo Plata',   pos: 'FW', club: 'Al Qadsiah',      age: 24 },
      { name: 'Jeremy Sarmiento',pos: 'FW', club: 'Brighton',        age: 23 },
      { name: 'Hernán Galíndez', pos: 'GK', club: 'Aucas',          age: 35 },
    ],
  },
  VEN: {
    capital: 'Caracas', population: '28M', continent: 'South America',
    fifaRanking: 54, wcAppearances: 0, bestResult: '(First World Cup appearance)',
    funFact: 'Venezuela would make history as the only CONMEBOL nation never to have appeared at a World Cup, until qualifying for 2026.',
    players: [
      { name: 'Josef Martínez',  pos: 'FW', club: 'Atlanta United',  age: 31 },
      { name: 'Yeferson Soteldo',pos: 'FW', club: 'Santos',          age: 28 },
      { name: 'Rómulo Otero',    pos: 'MF', club: 'Athletico PR',   age: 32 },
      { name: 'Jefferson Savarino',pos:'FW',club: 'Real Salt Lake',  age: 28 },
      { name: 'Yangel Herrera',  pos: 'MF', club: 'Girona',          age: 26 },
      { name: 'Rafael Romo',     pos: 'GK', club: 'CD Lugo',         age: 35 },
    ],
  },
  BOL: {
    capital: 'Sucre / La Paz', population: '12M', continent: 'South America',
    fifaRanking: 88, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Bolivia plays home games at the Estadio Hernando Siles in La Paz, at 3,637 meters above sea level — the highest major stadium in the world.',
    players: [
      { name: 'Marcelo Moreno',  pos: 'FW', club: 'Cruzeiro',        age: 37 },
      { name: 'Ramiro Vaca',     pos: 'MF', club: 'The Strongest',   age: 33 },
      { name: 'Roberto Fernández',pos:'MF', club: 'Wilstermann',     age: 29 },
      { name: 'Jairo Quinteros', pos: 'DF', club: 'The Strongest',   age: 29 },
      { name: 'Luciano Ursino',  pos: 'MF', club: 'The Strongest',   age: 27 },
      { name: 'Gustavo Viscarra',pos: 'GK', club: 'Bolívar',         age: 33 },
    ],
  },
  URU: {
    capital: 'Montevideo', population: '3.5M', continent: 'South America',
    fifaRanking: 20, wcAppearances: 14, bestResult: 'Champions (1930, 1950)',
    funFact: 'Uruguay are two-time World Champions despite having a smaller population than most mid-sized cities.',
    players: [
      { name: 'Darwin Núñez',    pos: 'FW', club: 'Liverpool',       age: 25 },
      { name: 'Federico Valverde',pos:'MF', club: 'Real Madrid',     age: 26 },
      { name: 'Rodrigo Bentancur',pos:'MF', club: 'Tottenham',       age: 27 },
      { name: 'Giorgian De Arrascaeta',pos:'MF',club:'Flamengo',     age: 30 },
      { name: 'Facundo Pellistri',pos: 'FW', club: 'Man United',     age: 23 },
      { name: 'Sergio Rochet',   pos: 'GK', club: 'Nacional',        age: 30 },
    ],
  },
  NZL: {
    capital: 'Wellington', population: '5M', continent: 'Oceania',
    fifaRanking: 96, wcAppearances: 2, bestResult: 'Group Stage',
    funFact: 'New Zealand\'s "All Whites" went unbeaten at the 2010 World Cup, drawing all three group games including against defending champions Italy.',
    players: [
      { name: 'Chris Wood',      pos: 'FW', club: 'Nottm Forest',    age: 33 },
      { name: 'Clayton Lewis',   pos: 'MF', club: 'Yokohama F. Marinos',age:28 },
      { name: 'Matt Garbett',    pos: 'MF', club: 'RKC Waalwijk',   age: 26 },
      { name: 'Liberato Cacace', pos: 'DF', club: 'Empoli',          age: 24 },
      { name: 'Sarpreet Singh',  pos: 'MF', club: 'FC Zürich',       age: 26 },
      { name: 'Oliver Sail',     pos: 'GK', club: 'FC Lugano',       age: 26 },
    ],
  },
};
