export const TEAM_DATA = {
  ARG: {
    nickname: 'La Albiceleste', confederation: 'CONMEBOL', language: 'Spanish',
    colors: { primary: '#75AADB', secondary: '#FFFFFF' },
    capital: 'Buenos Aires', population: '46M', continent: 'South America',
    fifaRanking: 1, fifaRankingPrev: 1, wcAppearances: 18, bestResult: 'Champions (1978, 1986, 2022)',
    titles: ['1978', '1986', '2022'], firstAppearance: 1930,
    honors: ['World Cup ×3 (1978, 1986, 2022)', 'Copa América ×16', 'Finalissima 2022'],
    rivals: ['BRA', 'ENG'], qualification: 'CONMEBOL — 1st place',
    manager: { name: 'Lionel Scaloni', since: 2018, nationality: 'Argentina' },
    captain: 'Lionel Messi', homeStadium: 'Estadio Monumental, Buenos Aires', formation: '4-3-3',
    funFact: 'Argentina are the reigning World Champions and have won a record 15 Copa América titles.',
    funFacts: [
      'Argentina are the reigning World Champions, lifting the 2022 trophy in one of the greatest finals ever.',
      'They hold a record 16 Copa América titles, level at the top of South American football.',
      'Lionel Messi is the most-capped player in Argentine history and won the 2022 Golden Ball at age 35.',
    ],
    players: [
      { name: 'Emiliano Martínez',  pos: 'GK', club: 'Aston Villa',     age: 33, number: 23, caps: 48,  goals: 0 },
      { name: 'Rodrigo De Paul',    pos: 'MF', club: 'Atlético Madrid', age: 31, number: 7,  caps: 75,  goals: 3 },
      { name: 'Enzo Fernández',     pos: 'MF', club: 'Chelsea',         age: 25, number: 24, caps: 40,  goals: 4 },
      { name: 'Alexis Mac Allister',pos: 'MF', club: 'Liverpool',       age: 26, number: 20, caps: 40,  goals: 3 },
      { name: 'Lionel Messi',       pos: 'FW', club: 'Inter Miami',     age: 38, number: 10, caps: 191, goals: 112, isCaptain: true, isStar: true },
      { name: 'Lautaro Martínez',   pos: 'FW', club: 'Inter Milan',     age: 27, number: 22, caps: 70,  goals: 32, isStar: true },
    ],
  },
  BRA: {
    nickname: 'Seleção', confederation: 'CONMEBOL', language: 'Portuguese',
    colors: { primary: '#009C3B', secondary: '#FFDF00' },
    capital: 'Brasília', population: '215M', continent: 'South America',
    fifaRanking: 5, fifaRankingPrev: 3, wcAppearances: 22, bestResult: 'Champions (1958, 1962, 1970, 1994, 2002)',
    titles: ['1958', '1962', '1970', '1994', '2002'], firstAppearance: 1930,
    honors: ['World Cup ×5 (record)', 'Copa América ×9', 'Confederations Cup ×4'],
    rivals: ['ARG'], qualification: 'CONMEBOL — qualified',
    manager: { name: 'Carlo Ancelotti', since: 2025, nationality: 'Italy' },
    captain: 'Marquinhos', homeStadium: 'Maracanã, Rio de Janeiro', formation: '4-2-3-1',
    funFact: 'Brazil is the only nation to have played in every World Cup and the most successful with 5 titles.',
    funFacts: [
      'Brazil is the only nation to have played in every single World Cup finals tournament.',
      'With 5 titles they are the most successful side in World Cup history.',
      'Carlo Ancelotti became the first foreign manager to lead the Seleção at a World Cup.',
    ],
    players: [
      { name: 'Alisson Becker', pos: 'GK', club: 'Liverpool',    age: 33, number: 1,  caps: 75, goals: 0 },
      { name: 'Casemiro',       pos: 'MF', club: 'Man United',   age: 34, number: 5,  caps: 78, goals: 7 },
      { name: 'Raphinha',       pos: 'MF', club: 'Barcelona',    age: 29, number: 11, caps: 45, goals: 12 },
      { name: 'Rodrygo',        pos: 'FW', club: 'Real Madrid',  age: 24, number: 10, caps: 38, goals: 8 },
      { name: 'Vinicius Jr.',   pos: 'FW', club: 'Real Madrid',  age: 25, number: 7,  caps: 45, goals: 11, isStar: true },
      { name: 'Endrick',        pos: 'FW', club: 'Real Madrid',  age: 19, number: 9,  caps: 18, goals: 5, isStar: true },
    ],
  },
  FRA: {
    nickname: 'Les Bleus', confederation: 'UEFA', language: 'French',
    colors: { primary: '#002654', secondary: '#ED2939' },
    capital: 'Paris', population: '68M', continent: 'Europe',
    fifaRanking: 2, fifaRankingPrev: 2, wcAppearances: 16, bestResult: 'Champions (1998, 2018)',
    titles: ['1998', '2018'], firstAppearance: 1930,
    honors: ['World Cup ×2 (1998, 2018)', 'Euro ×2 (1984, 2000)', 'Nations League 2021'],
    rivals: ['GER', 'ENG', 'ITA'], qualification: 'UEFA — group winners',
    manager: { name: 'Didier Deschamps', since: 2012, nationality: 'France' },
    captain: 'Kylian Mbappé', homeStadium: 'Stade de France, Paris', formation: '4-2-3-1',
    funFact: 'France\'s "Les Bleus" boast one of the most talented generations in football history.',
    funFacts: [
      'France reached back-to-back World Cup finals in 2018 and 2022, winning the first.',
      'Didier Deschamps has won the World Cup as both captain (1998) and manager (2018).',
      'Kylian Mbappé scored a hat-trick in the 2022 final — only the second player ever to do so.',
    ],
    players: [
      { name: 'Mike Maignan',       pos: 'GK', club: 'AC Milan',        age: 30, number: 16, caps: 30, goals: 0 },
      { name: 'Aurélien Tchouaméni',pos: 'MF', club: 'Real Madrid',     age: 26, number: 8,  caps: 40, goals: 3 },
      { name: 'Eduardo Camavinga',  pos: 'MF', club: 'Real Madrid',     age: 23, number: 6,  caps: 32, goals: 1 },
      { name: 'Antoine Griezmann',  pos: 'FW', club: 'Atlético Madrid', age: 35, number: 7,  caps: 137, goals: 44 },
      { name: 'Marcus Thuram',      pos: 'FW', club: 'Inter Milan',     age: 28, number: 9,  caps: 30, goals: 7 },
      { name: 'Kylian Mbappé',      pos: 'FW', club: 'Real Madrid',     age: 27, number: 10, caps: 90, goals: 50, isCaptain: true, isStar: true },
    ],
  },
  ENG: {
    nickname: 'Three Lions', confederation: 'UEFA', language: 'English',
    colors: { primary: '#FFFFFF', secondary: '#001489' },
    capital: 'London', population: '57M', continent: 'Europe',
    fifaRanking: 5, fifaRankingPrev: 4, wcAppearances: 17, bestResult: 'Champions (1966)',
    titles: ['1966'], firstAppearance: 1950,
    honors: ['World Cup 1966', 'Euro Runners-up 2020 & 2024'],
    rivals: ['GER', 'SCO', 'ARG'], qualification: 'UEFA — group winners',
    manager: { name: 'Thomas Tuchel', since: 2025, nationality: 'Germany' },
    captain: 'Harry Kane', homeStadium: 'Wembley Stadium, London', formation: '4-3-3',
    funFact: 'England invented the modern game of football and hosted the first Atlanta Soccer News World Cup in Europe in 1966.',
    funFacts: [
      'England won their only World Cup on home soil in 1966.',
      'They have reached two of the last three European Championship finals.',
      'Harry Kane is England\'s all-time leading goalscorer, passing Wayne Rooney in 2023.',
    ],
    players: [
      { name: 'Jordan Pickford', pos: 'GK', club: 'Everton',      age: 32, number: 1,  caps: 75, goals: 0 },
      { name: 'Declan Rice',     pos: 'MF', club: 'Arsenal',      age: 27, number: 4,  caps: 65, goals: 5 },
      { name: 'Jude Bellingham', pos: 'MF', club: 'Real Madrid',  age: 22, number: 10, caps: 40, goals: 8, isStar: true },
      { name: 'Phil Foden',      pos: 'MF', club: 'Man City',     age: 26, number: 11, caps: 45, goals: 4 },
      { name: 'Bukayo Saka',     pos: 'FW', club: 'Arsenal',      age: 24, number: 7,  caps: 45, goals: 13, isStar: true },
      { name: 'Harry Kane',      pos: 'FW', club: 'Bayern Munich',age: 32, number: 9,  caps: 105, goals: 70, isCaptain: true, isStar: true },
    ],
  },
  ESP: {
    nickname: 'La Roja', confederation: 'UEFA', language: 'Spanish',
    colors: { primary: '#C60B1E', secondary: '#FFC400' },
    capital: 'Madrid', population: '47M', continent: 'Europe',
    fifaRanking: 3, fifaRankingPrev: 8, wcAppearances: 16, bestResult: 'Champions (2010)',
    titles: ['2010'], firstAppearance: 1934,
    honors: ['World Cup 2010', 'Euro ×4 (1964, 2008, 2012, 2024)', 'Nations League 2023'],
    rivals: ['POR', 'ITA'], qualification: 'UEFA — group winners',
    manager: { name: 'Luis de la Fuente', since: 2022, nationality: 'Spain' },
    captain: 'Álvaro Morata', homeStadium: 'La Cartuja, Seville', formation: '4-3-3',
    funFact: 'Spain\'s tiki-taka style revolutionized modern football, winning three consecutive major tournaments 2008-2012.',
    funFacts: [
      'Spain won three straight major tournaments (Euro 2008, World Cup 2010, Euro 2012).',
      'They lifted Euro 2024 with a record seven wins from seven games.',
      'Lamine Yamal became the youngest goalscorer in European Championship history at 16.',
    ],
    players: [
      { name: 'Unai Simón',    pos: 'GK', club: 'Athletic Club',age: 28, number: 23, caps: 45, goals: 0 },
      { name: 'Rodri',         pos: 'MF', club: 'Man City',     age: 29, number: 16, caps: 60, goals: 4, isStar: true },
      { name: 'Pedri',         pos: 'MF', club: 'Barcelona',    age: 23, number: 8,  caps: 35, goals: 3, isStar: true },
      { name: 'Dani Olmo',     pos: 'MF', club: 'Barcelona',    age: 27, number: 10, caps: 45, goals: 11 },
      { name: 'Álvaro Morata', pos: 'FW', club: 'AC Milan',     age: 33, number: 7,  caps: 85, goals: 38, isCaptain: true },
      { name: 'Lamine Yamal',  pos: 'FW', club: 'Barcelona',    age: 18, number: 19, caps: 25, goals: 7, isStar: true },
    ],
  },
  GER: {
    nickname: 'Die Mannschaft', confederation: 'UEFA', language: 'German',
    colors: { primary: '#000000', secondary: '#DD0000' },
    capital: 'Berlin', population: '84M', continent: 'Europe',
    fifaRanking: 13, fifaRankingPrev: 16, wcAppearances: 20, bestResult: 'Champions (1954, 1974, 1990, 2014)',
    titles: ['1954', '1974', '1990', '2014'], firstAppearance: 1934,
    honors: ['World Cup ×4', 'Euro ×3 (1972, 1980, 1996)', 'Confederations Cup 2017'],
    rivals: ['NED', 'ENG', 'ITA'], qualification: 'UEFA — group winners',
    manager: { name: 'Julian Nagelsmann', since: 2023, nationality: 'Germany' },
    captain: 'Joshua Kimmich', homeStadium: 'Allianz Arena, Munich', formation: '4-2-3-1',
    funFact: 'Germany hosted the 2006 World Cup "Summer Fairy Tale" and are the most successful European nation with 4 titles.',
    funFacts: [
      'Germany have reached a record 8 World Cup finals, winning four.',
      'Their 7-1 demolition of hosts Brazil in the 2014 semi-final is one of football\'s most famous results.',
      'Miroslav Klose is the all-time top scorer in World Cup history with 16 goals.',
    ],
    players: [
      { name: 'Manuel Neuer',   pos: 'GK', club: 'Bayern Munich',    age: 40, number: 1,  caps: 124, goals: 0 },
      { name: 'Joshua Kimmich', pos: 'MF', club: 'Bayern Munich',    age: 31, number: 6,  caps: 100, goals: 7, isCaptain: true },
      { name: 'Leon Goretzka',  pos: 'MF', club: 'Bayern Munich',    age: 31, number: 8,  caps: 57,  goals: 14 },
      { name: 'Florian Wirtz',  pos: 'MF', club: 'Bayer Leverkusen', age: 22, number: 10, caps: 30,  goals: 6, isStar: true },
      { name: 'Jamal Musiala',  pos: 'MF', club: 'Bayern Munich',    age: 22, number: 14, caps: 40,  goals: 8, isStar: true },
      { name: 'Kai Havertz',    pos: 'FW', club: 'Arsenal',          age: 26, number: 7,  caps: 50,  goals: 18 },
    ],
  },
  POR: {
    nickname: 'Seleção das Quinas', confederation: 'UEFA', language: 'Portuguese',
    colors: { primary: '#FF0000', secondary: '#006600' },
    capital: 'Lisbon', population: '10M', continent: 'Europe',
    fifaRanking: 6, fifaRankingPrev: 6, wcAppearances: 9, bestResult: '3rd Place (1966)',
    titles: [], firstAppearance: 1966,
    honors: ['Euro 2016', 'Nations League 2019 & 2025'],
    rivals: ['ESP'], qualification: 'UEFA — group winners',
    manager: { name: 'Roberto Martínez', since: 2023, nationality: 'Spain' },
    captain: 'Cristiano Ronaldo', homeStadium: 'Estádio da Luz, Lisbon', formation: '4-3-3',
    funFact: 'Portugal\'s "Golden Generation" won Euro 2016 and the inaugural UEFA Nations League in 2019.',
    funFacts: [
      'Portugal won their first major trophy at Euro 2016, beating hosts France in the final.',
      'They have lifted two UEFA Nations League titles (2019 and 2025).',
      'Cristiano Ronaldo is the all-time leading goalscorer in men\'s international football.',
    ],
    players: [
      { name: 'Diogo Costa',       pos: 'GK', club: 'Porto',       age: 25, number: 22, caps: 30,  goals: 0 },
      { name: 'Vitinha',           pos: 'MF', club: 'PSG',         age: 26, number: 16, caps: 35,  goals: 3 },
      { name: 'Bruno Fernandes',   pos: 'MF', club: 'Man United',  age: 31, number: 8,  caps: 80,  goals: 24, isStar: true },
      { name: 'Bernardo Silva',    pos: 'MF', club: 'Man City',    age: 31, number: 10, caps: 100, goals: 12 },
      { name: 'Rafael Leão',       pos: 'FW', club: 'AC Milan',    age: 26, number: 17, caps: 40,  goals: 6, isStar: true },
      { name: 'Cristiano Ronaldo', pos: 'FW', club: 'Al Nassr',    age: 41, number: 7,  caps: 220, goals: 138, isCaptain: true, isStar: true },
    ],
  },
  NED: {
    nickname: 'Oranje', confederation: 'UEFA', language: 'Dutch',
    colors: { primary: '#EC7000', secondary: '#21468B' },
    capital: 'Amsterdam', population: '17M', continent: 'Europe',
    fifaRanking: 7, fifaRankingPrev: 7, wcAppearances: 11, bestResult: 'Runners-up (1974, 1978, 2010)',
    titles: [], firstAppearance: 1934,
    honors: ['Euro 1988', 'World Cup Runners-up ×3 (1974, 1978, 2010)'],
    rivals: ['GER', 'BEL'], qualification: 'UEFA — group winners',
    manager: { name: 'Ronald Koeman', since: 2023, nationality: 'Netherlands' },
    captain: 'Virgil van Dijk', homeStadium: 'Johan Cruyff Arena, Amsterdam', formation: '4-3-3',
    funFact: 'The Netherlands invented "Total Football" in the 1970s, revolutionizing the game with players like Johan Cruyff.',
    funFacts: [
      'The Netherlands pioneered "Total Football" under Rinus Michels and Johan Cruyff in the 1970s.',
      'They are the most successful nation never to win the World Cup, with three runners-up finishes.',
      'Their lone major title came at Euro 1988, inspired by Marco van Basten\'s iconic volley.',
    ],
    players: [
      { name: 'Mark Flekken',    pos: 'GK', club: 'Brentford',      age: 31, number: 1,  caps: 12, goals: 0 },
      { name: 'Virgil van Dijk', pos: 'DF', club: 'Liverpool',      age: 34, number: 4,  caps: 80, goals: 8, isCaptain: true, isStar: true },
      { name: 'Frenkie de Jong', pos: 'MF', club: 'Barcelona',      age: 29, number: 21, caps: 55, goals: 3, isStar: true },
      { name: 'Tijjani Reijnders',pos:'MF', club: 'AC Milan',       age: 26, number: 14, caps: 25, goals: 4 },
      { name: 'Cody Gakpo',      pos: 'FW', club: 'Liverpool',      age: 26, number: 11, caps: 35, goals: 12, isStar: true },
      { name: 'Memphis Depay',   pos: 'FW', club: 'Atlético Madrid',age: 32, number: 10, caps: 100, goals: 52 },
    ],
  },
  ITA: {
    capital: 'Rome', population: '60M', continent: 'Europe',
    fifaRanking: 9, wcAppearances: 18, bestResult: 'Champions (1934, 1938, 1982, 2006)',
    funFact: 'Italy is one of only two nations to win the World Cup as host, and won back-to-back titles in 1934 and 1938.',
    players: [
      { name: 'Gianluigi Donnarumma', pos: 'GK', club: 'PSG',            age: 26 },
      { name: 'Nicolò Barella',       pos: 'MF', club: 'Inter Milan',     age: 27 },
      { name: 'Sandro Tonali',        pos: 'MF', club: 'Newcastle',       age: 24 },
      { name: 'Federico Chiesa',      pos: 'FW', club: 'Liverpool',       age: 28 },
      { name: 'Giacomo Raspadori',    pos: 'FW', club: 'Napoli',          age: 25 },
      { name: 'Alessandro Bastoni',   pos: 'DF', club: 'Inter Milan',     age: 26 },
    ],
  },
  BEL: {
    nickname: 'Red Devils', confederation: 'UEFA', language: 'Dutch / French',
    colors: { primary: '#E30613', secondary: '#FDDA24' },
    capital: 'Brussels', population: '11M', continent: 'Europe',
    fifaRanking: 10, fifaRankingPrev: 5, wcAppearances: 13, bestResult: '3rd Place (2018)',
    titles: [], firstAppearance: 1930,
    honors: ['World Cup 3rd Place (2018)', 'Olympic Gold (1920)'],
    rivals: ['NED', 'FRA'], qualification: 'UEFA — group winners',
    manager: { name: 'Rudi Garcia', since: 2025, nationality: 'France' },
    captain: 'Kevin De Bruyne', homeStadium: 'King Baudouin Stadium, Brussels', formation: '4-3-3',
    funFact: 'Belgium\'s "Golden Generation" reached their highest-ever Atlanta Soccer News ranking of #1 in 2018.',
    funFacts: [
      'Belgium\'s "Golden Generation" topped the FIFA Rankings for a then-record stretch from 2018.',
      'Their best World Cup finish was 3rd place in 2018, beating England in the playoff.',
      'Kevin De Bruyne is widely regarded as one of the finest playmakers of his generation.',
    ],
    players: [
      { name: 'Thibaut Courtois',pos: 'GK', club: 'Real Madrid',  age: 34, number: 1,  caps: 105, goals: 0, isStar: true },
      { name: 'Wout Faes',       pos: 'DF', club: 'Leicester',    age: 27, number: 4,  caps: 25,  goals: 1 },
      { name: 'Amadou Onana',    pos: 'MF', club: 'Aston Villa',  age: 23, number: 8,  caps: 30,  goals: 2 },
      { name: 'Kevin De Bruyne', pos: 'MF', club: 'Napoli',       age: 35, number: 7,  caps: 110, goals: 30, isCaptain: true, isStar: true },
      { name: 'Jeremy Doku',     pos: 'FW', club: 'Man City',     age: 23, number: 11, caps: 30,  goals: 4, isStar: true },
      { name: 'Romelu Lukaku',   pos: 'FW', club: 'Napoli',       age: 32, number: 9,  caps: 120, goals: 85 },
    ],
  },
  CRO: {
    nickname: 'Vatreni', confederation: 'UEFA', language: 'Croatian',
    colors: { primary: '#FF0000', secondary: '#FFFFFF' },
    capital: 'Zagreb', population: '4M', continent: 'Europe',
    fifaRanking: 11, fifaRankingPrev: 10, wcAppearances: 7, bestResult: 'Runners-up (2018)',
    titles: [], firstAppearance: 1998,
    honors: ['World Cup Runners-up (2018)', 'World Cup 3rd Place (2022)'],
    rivals: ['SRB', 'ITA'], qualification: 'UEFA — group winners',
    manager: { name: 'Zlatko Dalić', since: 2017, nationality: 'Croatia' },
    captain: 'Luka Modrić', homeStadium: 'Stadion Maksimir, Zagreb', formation: '4-3-3',
    funFact: 'Croatia reached back-to-back World Cup semi-finals (2018, 2022) making them one of the most consistent small nations.',
    funFacts: [
      'Croatia, a nation of under 4 million, reached the 2018 World Cup final and finished 3rd in 2022.',
      'Luka Modrić won the 2018 Ballon d\'Or, ending a decade of Messi–Ronaldo dominance.',
      'They have a remarkable record in penalty shootouts at major tournaments.',
    ],
    players: [
      { name: 'Dominik Livaković',pos:'GK', club: 'Fenerbahçe',     age: 29, number: 1,  caps: 45, goals: 0 },
      { name: 'Joško Gvardiol',  pos: 'DF', club: 'Man City',       age: 23, number: 20, caps: 35, goals: 3, isStar: true },
      { name: 'Luka Modrić',     pos: 'MF', club: 'Real Madrid',    age: 41, number: 10, caps: 185, goals: 27, isCaptain: true, isStar: true },
      { name: 'Mateo Kovačić',   pos: 'MF', club: 'Man City',       age: 32, number: 8,  caps: 100, goals: 5 },
      { name: 'Nikola Vlašić',   pos: 'MF', club: 'West Ham',       age: 28, number: 13, caps: 50, goals: 6 },
      { name: 'Andrej Kramarić', pos: 'FW', club: 'Hoffenheim',     age: 34, number: 9,  caps: 95, goals: 27, isStar: true },
    ],
  },
  SUI: {
    nickname: 'Nati', confederation: 'UEFA', language: 'German / French / Italian',
    colors: { primary: '#FF0000', secondary: '#FFFFFF' },
    capital: 'Bern', population: '8.7M', continent: 'Europe',
    fifaRanking: 20, fifaRankingPrev: 19, wcAppearances: 12, bestResult: 'Quarter-finals (1934, 1938, 1954)',
    titles: [], firstAppearance: 1934,
    honors: ['World Cup Quarter-finals ×3', 'Consistent major-tournament qualifier'],
    rivals: ['GER', 'ITA'], qualification: 'UEFA — group winners',
    manager: { name: 'Murat Yakin', since: 2021, nationality: 'Switzerland' },
    captain: 'Granit Xhaka', homeStadium: 'St. Jakob-Park, Basel', formation: '4-2-3-1',
    funFact: 'Switzerland co-hosted the 1954 World Cup and has been a consistent qualifier for major tournaments.',
    funFacts: [
      'Switzerland have qualified for every World Cup since 2006 — a model of consistency.',
      'They knocked out reigning champions France on penalties at Euro 2020.',
      'The Nati reached the quarter-finals at Euro 2024, falling narrowly to England.',
    ],
    players: [
      { name: 'Yann Sommer',   pos: 'GK', club: 'Inter Milan',      age: 37, number: 1,  caps: 95, goals: 0, isStar: true },
      { name: 'Silvan Widmer', pos: 'DF', club: 'Mainz',            age: 31, number: 2,  caps: 35, goals: 1 },
      { name: 'Granit Xhaka',  pos: 'MF', club: 'Bayer Leverkusen', age: 33, number: 10, caps: 135, goals: 14, isCaptain: true, isStar: true },
      { name: 'Remo Freuler',  pos: 'MF', club: 'Bologna',          age: 32, number: 8,  caps: 60, goals: 3 },
      { name: 'Xherdan Shaqiri',pos: 'FW', club: 'Chicago Fire',    age: 34, number: 23, caps: 125, goals: 32, isStar: true },
      { name: 'Breel Embolo',  pos: 'FW', club: 'Monaco',           age: 29, number: 7,  caps: 70, goals: 16 },
    ],
  },
  DEN: {
    capital: 'Copenhagen', population: '5.9M', continent: 'Europe',
    fifaRanking: 23, wcAppearances: 5, bestResult: 'Quarter-finals (1998)',
    funFact: 'Denmark won Euro 1992 despite not qualifying — they were called up as a late replacement for Yugoslavia.',
    players: [
      { name: 'Christian Eriksen', pos: 'MF', club: 'Man United',    age: 34 },
      { name: 'Pierre-Emile Højbjerg', pos: 'MF', club: 'Marseille', age: 30 },
      { name: 'Rasmus Højlund',   pos: 'FW', club: 'Man United',     age: 23 },
      { name: 'Joakim Mæhle',     pos: 'DF', club: 'Atalanta',       age: 28 },
      { name: 'Andreas Skov Olsen',pos:'FW', club: 'Club Brugge',    age: 25 },
      { name: 'Kasper Schmeichel', pos: 'GK', club: 'Anderlecht',    age: 39 },
    ],
  },
  AUT: {
    nickname: 'Das Team', confederation: 'UEFA', language: 'German',
    colors: { primary: '#ED2939', secondary: '#FFFFFF' },
    capital: 'Vienna', population: '9M', continent: 'Europe',
    fifaRanking: 25, fifaRankingPrev: 25, wcAppearances: 7, bestResult: '3rd Place (1954)',
    titles: [], firstAppearance: 1934,
    honors: ['World Cup 3rd Place (1954)', 'Legendary 1930s "Wunderteam"'],
    rivals: ['GER'], qualification: 'UEFA — group winners',
    manager: { name: 'Ralf Rangnick', since: 2022, nationality: 'Germany' },
    captain: 'David Alaba', homeStadium: 'Ernst-Happel-Stadion, Vienna', formation: '4-2-3-1',
    funFact: 'Austria hosted and reached the semi-finals of the 1934 World Cup with their legendary "Wunderteam".',
    funFacts: [
      'Austria\'s 1930s "Wunderteam" was one of the most admired sides of the pre-war era.',
      'Under Ralf Rangnick they topped a tough group ahead of France at Euro 2024.',
      'David Alaba has won the Champions League with both Bayern Munich and Real Madrid.',
    ],
    players: [
      { name: 'Patrick Pentz',    pos: 'GK', club: 'Bayer Leverkusen',age: 27, number: 1,  caps: 25, goals: 0 },
      { name: 'David Alaba',      pos: 'DF', club: 'Real Madrid',    age: 33, number: 8,  caps: 105, goals: 15, isCaptain: true, isStar: true },
      { name: 'Konrad Laimer',    pos: 'MF', club: 'Bayern Munich', age: 27, number: 11, caps: 45, goals: 3 },
      { name: 'Marcel Sabitzer',  pos: 'MF', club: 'Dortmund',      age: 31, number: 9,  caps: 80, goals: 14, isStar: true },
      { name: 'Florian Grillitsch',pos:'MF', club: 'Ajax',          age: 30, number: 6,  caps: 45, goals: 1 },
      { name: 'Marko Arnautović', pos: 'FW', club: 'Man United',    age: 37, number: 7,  caps: 120, goals: 39, isStar: true },
    ],
  },
  SRB: {
    capital: 'Belgrade', population: '7M', continent: 'Europe',
    fifaRanking: 29, wcAppearances: 13, bestResult: '4th Place (1930, 1962) as Yugoslavia',
    funFact: 'Serbia (as Yugoslavia) was one of four teams at the very first World Cup in 1930.',
    players: [
      { name: 'Aleksandar Mitrović', pos: 'FW', club: 'Al Hilal',     age: 31 },
      { name: 'Luka Jović',          pos: 'FW', club: 'AC Milan',      age: 28 },
      { name: 'Filip Kostić',        pos: 'MF', club: 'Juventus',      age: 32 },
      { name: 'Dušan Tadić',         pos: 'FW', club: 'Fenerbahçe',   age: 37 },
      { name: 'Sergej Milinković-Savić', pos: 'MF', club: 'Al Hilal', age: 30 },
      { name: 'Predrag Rajković',    pos: 'GK', club: 'Mallorca',      age: 29 },
    ],
  },
  POL: {
    capital: 'Warsaw', population: '38M', continent: 'Europe',
    fifaRanking: 28, wcAppearances: 9, bestResult: '3rd Place (1974, 1982)',
    funFact: 'Robert Lewandowski became the first Polish player to win the Atlanta Soccer News Best Men\'s Player award in 2020.',
    players: [
      { name: 'Robert Lewandowski', pos: 'FW', club: 'Barcelona',     age: 37 },
      { name: 'Piotr Zieliński',    pos: 'MF', club: 'Inter Milan',   age: 32 },
      { name: 'Sebastian Szymański',pos: 'MF', club: 'Fenerbahçe',   age: 29 },
      { name: 'Matty Cash',         pos: 'DF', club: 'Aston Villa',   age: 28 },
      { name: 'Nicola Zalewski',    pos: 'MF', club: 'Roma',          age: 24 },
      { name: 'Wojciech Szczęsny',  pos: 'GK', club: 'Barcelona',    age: 36 },
    ],
  },
  TUR: {
    nickname: 'Ay-Yıldızlılar', confederation: 'UEFA', language: 'Turkish',
    colors: { primary: '#E30A17', secondary: '#FFFFFF' },
    capital: 'Ankara', population: '85M', continent: 'Europe/Asia',
    fifaRanking: 26, fifaRankingPrev: 27, wcAppearances: 2, bestResult: '3rd Place (2002)',
    titles: [], firstAppearance: 1954,
    honors: ['World Cup 3rd Place (2002)', 'Euro 2008 Semi-finals'],
    rivals: ['GRE'], qualification: 'UEFA — group winners',
    manager: { name: 'Vincenzo Montella', since: 2023, nationality: 'Italy' },
    captain: 'Hakan Çalhanoğlu', homeStadium: 'Atatürk Olympic Stadium, Istanbul', formation: '4-2-3-1',
    funFact: 'Turkey finished 3rd on their World Cup debut in 2002, with Hakan Şükür scoring the fastest-ever WC goal in 11 seconds.',
    funFacts: [
      'Turkey finished 3rd at the 2002 World Cup — their best-ever finish, on just their second appearance.',
      'Hakan Şükür scored the fastest goal in World Cup history (10.8 seconds) in the 2002 third-place match.',
      'A vibrant new generation led by Arda Güler reached the quarter-finals of Euro 2024.',
    ],
    players: [
      { name: 'Altay Bayındır',   pos: 'GK', club: 'Man United',      age: 27, number: 1,  caps: 25, goals: 0 },
      { name: 'Merih Demiral',    pos: 'DF', club: 'Al Ahli',         age: 27, number: 3,  caps: 50, goals: 5 },
      { name: 'Hakan Çalhanoğlu', pos: 'MF', club: 'Inter Milan',     age: 32, number: 10, caps: 95, goals: 20, isCaptain: true, isStar: true },
      { name: 'Yusuf Yazıcı',     pos: 'MF', club: 'LOSC Lille',      age: 28, number: 8,  caps: 40, goals: 7 },
      { name: 'Arda Güler',       pos: 'MF', club: 'Real Madrid',     age: 20, number: 15, caps: 25, goals: 6, isStar: true },
      { name: 'Kerem Aktürkoğlu', pos: 'FW', club: 'Galatasaray',    age: 26, number: 7,  caps: 35, goals: 9 },
    ],
  },
  SCO: {
    nickname: 'The Tartan Army', confederation: 'UEFA', language: 'English / Scots',
    colors: { primary: '#0065BF', secondary: '#FFFFFF' },
    capital: 'Edinburgh', population: '5.5M', continent: 'Europe',
    fifaRanking: 38, fifaRankingPrev: 39, wcAppearances: 8, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1954,
    honors: ['8 World Cup appearances', 'British Home Championship ×41'],
    rivals: ['ENG'], qualification: 'UEFA — group runners-up',
    manager: { name: 'Steve Clarke', since: 2019, nationality: 'Scotland' },
    captain: 'Andy Robertson', homeStadium: 'Hampden Park, Glasgow', formation: '3-4-2-1',
    funFact: 'Scotland played in the first-ever international football match against England in 1872, drawing 0-0.',
    funFacts: [
      'Scotland and England contested the first-ever international match in 1872 (0-0).',
      'The famously passionate "Tartan Army" travel in huge numbers to support the side.',
      'Steve Clarke ended a 25-year tournament drought by qualifying for Euro 2020.',
    ],
    players: [
      { name: 'Angus Gunn',      pos: 'GK', club: 'Norwich',        age: 29, number: 1,  caps: 20, goals: 0 },
      { name: 'Andy Robertson',  pos: 'DF', club: 'Liverpool',      age: 32, number: 3,  caps: 80, goals: 3, isCaptain: true, isStar: true },
      { name: 'Callum McGregor', pos: 'MF', club: 'Celtic',         age: 31, number: 4,  caps: 65, goals: 2 },
      { name: 'Scott McTominay', pos: 'MF', club: 'Napoli',         age: 29, number: 8,  caps: 60, goals: 12, isStar: true },
      { name: 'Ryan Christie',   pos: 'MF', club: 'Bournemouth',    age: 30, number: 10, caps: 50, goals: 5 },
      { name: 'Che Adams',       pos: 'FW', club: 'Torino',         age: 29, number: 9,  caps: 35, goals: 6 },
    ],
  },
  MAR: {
    nickname: 'Atlas Lions', confederation: 'CAF', language: 'Arabic / Berber',
    colors: { primary: '#C1272D', secondary: '#006233' },
    capital: 'Rabat', population: '37M', continent: 'Africa',
    fifaRanking: 14, fifaRankingPrev: 13, wcAppearances: 6, bestResult: 'Semi-finals (2022)',
    titles: [], firstAppearance: 1970,
    honors: ['World Cup 4th Place (2022)', 'Africa Cup of Nations (1976)'],
    rivals: ['ALG'], qualification: 'CAF — group winners',
    manager: { name: 'Walid Regragui', since: 2022, nationality: 'Morocco' },
    captain: 'Achraf Hakimi', homeStadium: 'Stade Prince Moulay Abdellah, Rabat', formation: '4-3-3',
    funFact: 'Morocco became the first African nation to reach a World Cup semi-final at Qatar 2022.',
    funFacts: [
      'Morocco made history as the first African and Arab nation to reach a World Cup semi-final (2022).',
      'On the way they knocked out Belgium, Spain and Portugal — a fairy-tale run.',
      'Goalkeeper Yassine Bounou was the hero of their 2022 penalty-shootout wins.',
    ],
    players: [
      { name: 'Yassine Bounou', pos: 'GK', club: 'Al Hilal',      age: 33, number: 1,  caps: 60, goals: 0, isStar: true },
      { name: 'Achraf Hakimi',  pos: 'DF', club: 'PSG',           age: 27, number: 2,  caps: 80, goals: 11, isCaptain: true, isStar: true },
      { name: 'Sofyan Amrabat', pos: 'MF', club: 'Al Batayih',    age: 29, number: 4,  caps: 55, goals: 1 },
      { name: 'Azzedine Ounahi',pos: 'MF', club: 'Marseille',     age: 25, number: 8,  caps: 35, goals: 4 },
      { name: 'Hakim Ziyech',   pos: 'FW', club: 'Galatasaray',  age: 33, number: 7,  caps: 60, goals: 20, isStar: true },
      { name: 'Youssef En-Nesyri', pos: 'FW', club: 'Fenerbahçe', age: 28, number: 19, caps: 75, goals: 22 },
    ],
  },
  SEN: {
    nickname: 'Lions of Teranga', confederation: 'CAF', language: 'French / Wolof',
    colors: { primary: '#00853F', secondary: '#FDEF42' },
    capital: 'Dakar', population: '17M', continent: 'Africa',
    fifaRanking: 18, fifaRankingPrev: 17, wcAppearances: 3, bestResult: 'Quarter-finals (2002)',
    titles: [], firstAppearance: 2002,
    honors: ['Africa Cup of Nations (2021)', 'World Cup Quarter-finals (2002)'],
    rivals: ['EGY', 'CIV'], qualification: 'CAF — group winners',
    manager: { name: 'Pape Thiaw', since: 2024, nationality: 'Senegal' },
    captain: 'Kalidou Koulibaly', homeStadium: 'Stade Abdoulaye Wade, Diamniadio', formation: '4-3-3',
    funFact: 'Senegal won the 2022 Africa Cup of Nations for the first time in their history.',
    funFacts: [
      'Senegal won their first-ever Africa Cup of Nations in 2021, beating Egypt on penalties.',
      'On their World Cup debut in 2002 they beat holders France and reached the quarter-finals.',
      'Sadio Mané is the talisman of a golden generation of Senegalese football.',
    ],
    players: [
      { name: 'Édouard Mendy',    pos: 'GK', club: 'Al Ahli',        age: 32, number: 16, caps: 45, goals: 0, isStar: true },
      { name: 'Kalidou Koulibaly',pos: 'DF', club: 'Al Hilal',       age: 34, number: 3,  caps: 80, goals: 6, isCaptain: true, isStar: true },
      { name: 'Idrissa Gueye',    pos: 'MF', club: 'Everton',        age: 36, number: 5,  caps: 100, goals: 10 },
      { name: 'Krepin Diatta',    pos: 'FW', club: 'Monaco',         age: 26, number: 11, caps: 40, goals: 5 },
      { name: 'Sadio Mané',       pos: 'FW', club: 'Al Nassr',       age: 34, number: 10, caps: 105, goals: 45, isStar: true },
      { name: 'Ismaïla Sarr',     pos: 'FW', club: 'Crystal Palace', age: 26, number: 18, caps: 55, goals: 12 },
    ],
  },
  NGA: {
    capital: 'Abuja', population: '220M', continent: 'Africa',
    fifaRanking: 35, wcAppearances: 7, bestResult: 'Round of 16 (1994, 1998, 2014)',
    funFact: 'Nigeria\'s Super Eagles won Olympic gold at Atlanta 1996, beating Argentina in the semi-final.',
    players: [
      { name: 'Victor Osimhen', pos: 'FW', club: 'Galatasaray',   age: 27 },
      { name: 'Ademola Lookman',pos: 'FW', club: 'Atalanta',      age: 27 },
      { name: 'Alex Iwobi',     pos: 'MF', club: 'Fulham',        age: 30 },
      { name: 'Calvin Bassey',  pos: 'DF', club: 'Fulham',        age: 25 },
      { name: 'Wilfred Ndidi',  pos: 'MF', club: 'Leicester',     age: 29 },
      { name: 'Stanley Nwabali',pos: 'GK', club: 'Chippa United', age: 28 },
    ],
  },
  EGY: {
    nickname: 'The Pharaohs', confederation: 'CAF', language: 'Arabic',
    colors: { primary: '#CE1126', secondary: '#FFFFFF' },
    capital: 'Cairo', population: '105M', continent: 'Africa',
    fifaRanking: 37, fifaRankingPrev: 36, wcAppearances: 4, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1934,
    honors: ['Africa Cup of Nations ×7 (record)'],
    rivals: ['ALG', 'SEN'], qualification: 'CAF — group winners',
    manager: { name: 'Hossam Hassan', since: 2024, nationality: 'Egypt' },
    captain: 'Mohamed Salah', homeStadium: 'Cairo International Stadium', formation: '4-2-3-1',
    funFact: 'Egypt is Africa\'s most successful nation at the Africa Cup of Nations, having won it a record 7 times.',
    funFacts: [
      'Egypt are the most successful side in Africa Cup of Nations history with 7 titles.',
      'They were the first African team to enter the World Cup, back in 1934.',
      'Mohamed Salah is Egypt\'s all-time leading scorer and a two-time Premier League Golden Boot winner.',
    ],
    players: [
      { name: 'Mohamed El-Shenawy',pos:'GK', club: 'Al Ahly',        age: 37, number: 1,  caps: 70, goals: 0 },
      { name: 'Tarek Hamed',      pos: 'MF', club: 'Zamalek',        age: 36, number: 17, caps: 60, goals: 1 },
      { name: 'Amr El Sulaya',    pos: 'MF', club: 'Al Qadsiah',     age: 26, number: 8,  caps: 40, goals: 3 },
      { name: 'Mohamed Salah',    pos: 'FW', club: 'Liverpool',       age: 33, number: 10, caps: 100, goals: 60, isCaptain: true, isStar: true },
      { name: 'Omar Marmoush',    pos: 'FW', club: 'Manchester City', age: 26, number: 9,  caps: 40, goals: 14, isStar: true },
      { name: 'Mostafa Mohamed',  pos: 'FW', club: 'Nantes',         age: 27, number: 19, caps: 45, goals: 12 },
    ],
  },
  CIV: {
    nickname: 'Les Éléphants', confederation: 'CAF', language: 'French',
    colors: { primary: '#FF8200', secondary: '#009E60' },
    capital: 'Yamoussoukro', population: '27M', continent: 'Africa',
    fifaRanking: 45, fifaRankingPrev: 41, wcAppearances: 3, bestResult: 'Group Stage',
    titles: [], firstAppearance: 2006,
    honors: ['Africa Cup of Nations ×3 (1992, 2015, 2023)'],
    rivals: ['GHA', 'SEN'], qualification: 'CAF — group winners',
    manager: { name: 'Emerse Faé', since: 2024, nationality: 'Ivory Coast' },
    captain: 'Franck Kessié', homeStadium: 'Stade Alassane Ouattara, Abidjan', formation: '4-3-3',
    funFact: 'Ivory Coast won the 2023 Africa Cup of Nations on home soil, defeating Nigeria in the final.',
    funFacts: [
      'Ivory Coast won the 2023 AFCON on home soil after an astonishing turnaround from the group stage.',
      'Their "golden generation" of Drogba, Touré and Eboué dominated African football in the 2000s.',
      'They have lifted three Africa Cup of Nations titles (1992, 2015, 2023).',
    ],
    players: [
      { name: 'Yahia Fofana',      pos: 'GK', club: 'Chelsea',       age: 28, number: 1,  caps: 20, goals: 0 },
      { name: 'Serge Aurier',      pos: 'DF', club: 'Villarreal',    age: 33, number: 19, caps: 75, goals: 3 },
      { name: 'Franck Kessié',     pos: 'MF', club: 'Al Ahli',       age: 29, number: 6,  caps: 80, goals: 16, isCaptain: true, isStar: true },
      { name: 'Ibrahim Sangaré',   pos: 'MF', club: 'Nottm Forest',  age: 27, number: 8,  caps: 50, goals: 3 },
      { name: 'Sébastien Haller',  pos: 'FW', club: 'Dortmund',      age: 31, number: 9,  caps: 45, goals: 18, isStar: true },
      { name: 'Wilfried Zaha',     pos: 'FW', club: 'Galatasaray',   age: 33, number: 11, caps: 40, goals: 8, isStar: true },
    ],
  },
  CMR: {
    capital: 'Yaoundé', population: '28M', continent: 'Africa',
    fifaRanking: 43, wcAppearances: 8, bestResult: 'Quarter-finals (1990)',
    funFact: 'Cameroon\'s Roger Milla became a World Cup legend at Italia 1990, famously celebrating goals with a hip-shake dance.',
    players: [
      { name: 'André-Frank Zambo Anguissa', pos: 'MF', club: 'Napoli',    age: 29 },
      { name: 'Vincent Aboubakar',          pos: 'FW', club: 'Al Qadsiah',age: 33 },
      { name: 'Martin Hongla',              pos: 'MF', club: 'Verona',     age: 27 },
      { name: 'Harold Moukoudi',            pos: 'DF', club: 'Charlotte FC',age: 28 },
      { name: 'Clinton Njie',               pos: 'FW', club: 'Gençlerbirliği',age: 31 },
      { name: 'André Onana',                pos: 'GK', club: 'Man United', age: 29 },
    ],
  },
  GHA: {
    nickname: 'Black Stars', confederation: 'CAF', language: 'English',
    colors: { primary: '#006B3F', secondary: '#FCD116' },
    capital: 'Accra', population: '33M', continent: 'Africa',
    fifaRanking: 60, fifaRankingPrev: 68, wcAppearances: 4, bestResult: 'Quarter-finals (2010)',
    titles: [], firstAppearance: 2006,
    honors: ['Africa Cup of Nations ×4', 'World Cup Quarter-finals (2010)'],
    rivals: ['NGA', 'CIV'], qualification: 'CAF — group winners',
    manager: { name: 'Otto Addo', since: 2024, nationality: 'Ghana' },
    captain: 'Thomas Partey', homeStadium: 'Accra Sports Stadium', formation: '4-3-3',
    funFact: 'Ghana\'s Black Stars were one penalty away from becoming the first African team to reach a World Cup semi-final in 2010.',
    funFacts: [
      'In 2010 Ghana came within a missed penalty of being the first African semi-finalist.',
      'The Black Stars have won the Africa Cup of Nations four times.',
      'Mohammed Kudus has emerged as one of Africa\'s most exciting attacking talents.',
    ],
    players: [
      { name: 'Lawrence Ati Zigi',pos: 'GK', club: 'St. Gallen',     age: 28, number: 1,  caps: 35, goals: 0 },
      { name: 'Tariq Lamptey',    pos: 'DF', club: 'Brighton',        age: 24, number: 2,  caps: 25, goals: 1 },
      { name: 'Thomas Partey',    pos: 'MF', club: 'Arsenal',         age: 32, number: 5,  caps: 55, goals: 14, isCaptain: true, isStar: true },
      { name: 'Mohammed Kudus',   pos: 'FW', club: 'West Ham',        age: 24, number: 20, caps: 35, goals: 10, isStar: true },
      { name: 'Jordan Ayew',      pos: 'FW', club: 'Leicester',       age: 33, number: 9,  caps: 95, goals: 24 },
      { name: 'Ernest Nuamah',    pos: 'FW', club: 'Olympique Lyon',  age: 21, number: 11, caps: 20, goals: 4 },
    ],
  },
  TUN: {
    nickname: 'Eagles of Carthage', confederation: 'CAF', language: 'Arabic',
    colors: { primary: '#E70013', secondary: '#FFFFFF' },
    capital: 'Tunis', population: '12M', continent: 'Africa',
    fifaRanking: 31, fifaRankingPrev: 41, wcAppearances: 6, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1978,
    honors: ['Africa Cup of Nations (2004)'],
    rivals: ['ALG', 'EGY'], qualification: 'CAF — group winners',
    manager: { name: 'Sami Trabelsi', since: 2025, nationality: 'Tunisia' },
    captain: 'Youssef Msakni', homeStadium: 'Stade Hammadi Agrebi, Radès', formation: '4-3-3',
    funFact: 'Tunisia was the first African team to win a World Cup match, beating Mexico 3-1 in 1978.',
    funFacts: [
      'Tunisia became the first African nation to win a World Cup match, beating Mexico 3-1 in 1978.',
      'They beat reigning champions France 1-0 in the 2022 group stage.',
      'The Eagles of Carthage won their lone Africa Cup of Nations on home soil in 2004.',
    ],
    players: [
      { name: 'Aymen Dahmen',     pos: 'GK', club: 'Montpellier',    age: 27, number: 16, caps: 25, goals: 0 },
      { name: 'Dylan Bronn',      pos: 'DF', club: 'Salernitana',    age: 28, number: 3,  caps: 40, goals: 3 },
      { name: 'Aïssa Laïdouni',   pos: 'MF', club: 'Union Berlin',   age: 28, number: 14, caps: 45, goals: 4 },
      { name: 'Hannibal Mejbri',  pos: 'MF', club: 'Burnley',        age: 22, number: 8,  caps: 35, goals: 2, isStar: true },
      { name: 'Youssef Msakni',   pos: 'FW', club: 'Al Arabi',       age: 34, number: 7,  caps: 95, goals: 22, isCaptain: true, isStar: true },
      { name: 'Wahbi Khazri',     pos: 'FW', club: 'Montpellier',    age: 33, number: 10, caps: 74, goals: 25 },
    ],
  },
  RSA: {
    nickname: 'Bafana Bafana',
    confederation: 'CAF',
    colors: { primary: '#007A4D', secondary: '#FFB81C' },
    language: 'English / Zulu',
    capital: 'Pretoria', population: '60M', continent: 'Africa',
    fifaRanking: 68, fifaRankingPrev: 64, wcAppearances: 3,
    bestResult: 'Group Stage (2010 host)',
    titles: [],
    firstAppearance: 1998,
    honors: ['Africa Cup of Nations (1996)', 'COSAFA Cup × 7'],
    rivals: ['NGA', 'GHA'],
    qualification: 'CAF — Group C winners',
    manager: { name: 'Hugo Broos', since: 2021, nationality: 'Belgium' },
    captain: 'Ronwen Williams',
    homeStadium: 'FNB Stadium, Johannesburg',
    formation: '4-3-3',
    funFact: 'South Africa hosted the first-ever World Cup on African soil in 2010, popularizing the vuvuzela worldwide.',
    funFacts: [
      'South Africa hosted the first-ever World Cup on African soil in 2010, popularizing the vuvuzela worldwide.',
      'Bafana Bafana won the 1996 Africa Cup of Nations on home soil in their first appearance after readmission to international football.',
      'Captain Ronwen Williams became a national hero at AFCON 2024, saving four penalties in a single shootout.',
    ],
    players: [
      { name: 'Ronwen Williams',  pos: 'GK', club: 'Mamelodi Sundowns', age: 33, number: 1,  caps: 60, goals: 0, isCaptain: true },
      { name: 'Siyanda Xulu',     pos: 'DF', club: 'Sekhukhune United',  age: 33, number: 5,  caps: 35, goals: 1 },
      { name: 'Mothobi Mvala',    pos: 'DF', club: 'Mamelodi Sundowns', age: 31, number: 4,  caps: 28, goals: 2 },
      { name: 'Aubrey Modiba',    pos: 'DF', club: 'Mamelodi Sundowns', age: 30, number: 3,  caps: 32, goals: 3 },
      { name: 'Teboho Mokoena',   pos: 'MF', club: 'Mamelodi Sundowns', age: 28, number: 8,  caps: 42, goals: 6 },
      { name: 'Themba Zwane',     pos: 'MF', club: 'Mamelodi Sundowns', age: 35, number: 10, caps: 38, goals: 9 },
      { name: 'Yusuf Maart',      pos: 'MF', club: 'Kaizer Chiefs',     age: 29, number: 6,  caps: 22, goals: 2 },
      { name: 'Percy Tau',        pos: 'FW', club: 'Al Ahly',           age: 31, number: 11, caps: 50, goals: 13, isStar: true },
      { name: 'Lyle Foster',      pos: 'FW', club: 'Burnley',           age: 25, number: 9,  caps: 20, goals: 5, isStar: true },
      { name: 'Evidence Makgopa', pos: 'FW', club: 'Orlando Pirates',   age: 25, number: 7,  caps: 24, goals: 6 },
      { name: 'Oswin Appollis',   pos: 'FW', club: 'Polokwane City',    age: 24, number: 17, caps: 15, goals: 3 },
    ],
  },
  JPN: {
    nickname: 'Samurai Blue', confederation: 'AFC', language: 'Japanese',
    colors: { primary: '#0A1D6E', secondary: '#FFFFFF' },
    capital: 'Tokyo', population: '125M', continent: 'Asia',
    fifaRanking: 17, fifaRankingPrev: 18, wcAppearances: 8, bestResult: 'Round of 16 (2002, 2010, 2018, 2022)',
    titles: [], firstAppearance: 1998,
    honors: ['AFC Asian Cup ×4 (record)'],
    rivals: ['KOR', 'AUS'], qualification: 'AFC — group winners',
    manager: { name: 'Hajime Moriyasu', since: 2018, nationality: 'Japan' },
    captain: 'Wataru Endo', homeStadium: 'Saitama Stadium 2002', formation: '3-4-2-1',
    funFact: 'Japan co-hosted the 2002 World Cup with South Korea, becoming the first Asian nation to host the tournament.',
    funFacts: [
      'Japan stunned Germany and Spain to top their group at the 2022 World Cup.',
      'They are the most successful Asian side in the AFC Asian Cup with four titles.',
      'A wave of Japanese stars now feature for top European clubs across the continent.',
    ],
    players: [
      { name: 'Shuichi Gonda', pos: 'GK', club: 'Shimizu S-Pulse',age: 35, number: 12, caps: 40, goals: 0 },
      { name: 'Wataru Endo',   pos: 'MF', club: 'Liverpool',      age: 31, number: 6,  caps: 65, goals: 3, isCaptain: true },
      { name: 'Daichi Kamada', pos: 'MF', club: 'Crystal Palace', age: 28, number: 15, caps: 40, goals: 8 },
      { name: 'Kaoru Mitoma',  pos: 'FW', club: 'Brighton',       age: 27, number: 11, caps: 35, goals: 8, isStar: true },
      { name: 'Takefusa Kubo', pos: 'FW', club: 'Real Sociedad',  age: 24, number: 20, caps: 40, goals: 6, isStar: true },
      { name: 'Ritsu Doan',    pos: 'FW', club: 'Freiburg',       age: 27, number: 8,  caps: 50, goals: 10 },
    ],
  },
  KOR: {
    nickname: 'Taegeuk Warriors',
    confederation: 'AFC',
    colors: { primary: '#CD2E3A', secondary: '#0047A0' },
    language: 'Korean',
    capital: 'Seoul', population: '52M', continent: 'Asia',
    fifaRanking: 22, fifaRankingPrev: 23, wcAppearances: 11,
    bestResult: '4th Place (2002)',
    titles: [],
    firstAppearance: 1954,
    honors: ['AFC Asian Cup (1956, 1960)', 'World Cup 4th Place (2002)'],
    rivals: ['JPN', 'IRN'],
    qualification: 'AFC — 3rd round group winners',
    manager: { name: 'Hong Myung-bo', since: 2024, nationality: 'South Korea' },
    captain: 'Son Heung-min',
    homeStadium: 'Seoul World Cup Stadium',
    formation: '4-2-3-1',
    funFact: 'South Korea became the first Asian nation to reach a World Cup semi-final as co-hosts in 2002.',
    funFacts: [
      'South Korea became the first Asian nation to reach a World Cup semi-final as co-hosts in 2002.',
      'They have qualified for 11 World Cups — more than any other Asian nation — including 10 in a row since 1986.',
      'Captain Son Heung-min is the highest-scoring Asian player in Premier League history.',
    ],
    players: [
      { name: 'Kim Seung-gyu',  pos: 'GK', club: 'Al-Shabab',      age: 35, number: 1,  caps: 75,  goals: 0 },
      { name: 'Kim Min-jae',    pos: 'DF', club: 'Bayern Munich',  age: 28, number: 4,  caps: 65,  goals: 4, isStar: true },
      { name: 'Kim Young-gwon', pos: 'DF', club: 'Ulsan HD',       age: 36, number: 19, caps: 110, goals: 6 },
      { name: 'Lee Myung-jae',  pos: 'DF', club: 'Jeonbuk',        age: 28, number: 13, caps: 18,  goals: 0 },
      { name: 'Hwang In-beom',  pos: 'MF', club: 'Feyenoord',      age: 29, number: 6,  caps: 65,  goals: 5 },
      { name: 'Lee Jae-sung',   pos: 'MF', club: 'Mainz 05',       age: 33, number: 17, caps: 90,  goals: 12 },
      { name: 'Son Heung-min',  pos: 'FW', club: 'LAFC',           age: 34, number: 7,  caps: 130, goals: 51, isCaptain: true, isStar: true },
      { name: 'Lee Kang-in',    pos: 'FW', club: 'PSG',            age: 24, number: 18, caps: 35,  goals: 8, isStar: true },
      { name: 'Hwang Hee-chan', pos: 'FW', club: 'Wolves',         age: 29, number: 11, caps: 60,  goals: 12 },
      { name: 'Oh Hyeon-gyu',   pos: 'FW', club: 'Genk',           age: 25, number: 9,  caps: 22,  goals: 4 },
      { name: 'Bae Jun-ho',     pos: 'MF', club: 'Stoke City',     age: 22, number: 14, caps: 12,  goals: 1 },
    ],
  },
  CZE: {
    nickname: 'Národní tým',
    confederation: 'UEFA',
    colors: { primary: '#11457E', secondary: '#D7141A' },
    language: 'Czech',
    capital: 'Prague', population: '10.7M', continent: 'Europe',
    fifaRanking: 40, fifaRankingPrev: 43, wcAppearances: 2,
    bestResult: 'Group Stage (2006) — Runners-up 1934, 1962 as Czechoslovakia',
    titles: [],
    firstAppearance: 1996,
    honors: ['Euro 1976 (as Czechoslovakia)', 'World Cup Runners-up 1934 & 1962 (as Czechoslovakia)', 'Euro 1996 Runners-up'],
    rivals: ['SVK', 'GER'],
    qualification: 'UEFA — qualifying group runners-up',
    manager: { name: 'Ivan Hašek', since: 2024, nationality: 'Czechia' },
    captain: 'Tomáš Souček',
    homeStadium: 'Fortuna Arena, Prague',
    formation: '4-2-3-1',
    funFact: 'As Czechoslovakia, the nation reached two World Cup finals (1934, 1962) and won Euro 1976 in the first major tournament decided by a penalty shootout — sealed by Antonín Panenka\'s iconic chip.',
    funFacts: [
      'As Czechoslovakia, the nation reached two World Cup finals (1934 & 1962).',
      'They won Euro 1976 via the first-ever shootout decided by Antonín Panenka\'s now-legendary chipped penalty.',
      'Striker Patrik Schick scored from the halfway line at Euro 2020 — one of the greatest goals in tournament history.',
    ],
    players: [
      { name: 'Jindřich Staněk',  pos: 'GK', club: 'Slavia Prague',     age: 29, number: 1,  caps: 18, goals: 0 },
      { name: 'Vladimír Coufal',  pos: 'DF', club: 'West Ham',          age: 33, number: 5,  caps: 55, goals: 1 },
      { name: 'Tomáš Vlček',      pos: 'DF', club: 'Slavia Prague',     age: 24, number: 2,  caps: 12, goals: 0 },
      { name: 'David Doudera',    pos: 'DF', club: 'Slavia Prague',     age: 27, number: 18, caps: 20, goals: 1 },
      { name: 'Tomáš Souček',     pos: 'MF', club: 'West Ham',          age: 31, number: 15, caps: 80, goals: 17, isCaptain: true },
      { name: 'Lukáš Provod',     pos: 'MF', club: 'Slavia Prague',     age: 29, number: 20, caps: 35, goals: 6 },
      { name: 'Antonín Barák',    pos: 'MF', club: 'Fiorentina',        age: 31, number: 8,  caps: 45, goals: 8 },
      { name: 'Patrik Schick',    pos: 'FW', club: 'Bayer Leverkusen',  age: 30, number: 10, caps: 50, goals: 21, isStar: true },
      { name: 'Adam Hložek',      pos: 'FW', club: 'Hoffenheim',        age: 23, number: 22, caps: 38, goals: 6, isStar: true },
      { name: 'Mojmír Chytil',    pos: 'FW', club: 'Slavia Prague',     age: 26, number: 9,  caps: 16, goals: 5 },
      { name: 'Václav Černý',     pos: 'FW', club: 'Rangers',           age: 28, number: 21, caps: 22, goals: 3 },
    ],
  },
  AUS: {
    nickname: 'Socceroos', confederation: 'AFC', language: 'English',
    colors: { primary: '#FFCD00', secondary: '#00843D' },
    capital: 'Canberra', population: '26M', continent: 'Oceania/Asia',
    fifaRanking: 25, fifaRankingPrev: 24, wcAppearances: 6, bestResult: 'Round of 16 (2006, 2022)',
    titles: [], firstAppearance: 1974,
    honors: ['AFC Asian Cup (2015)', 'OFC Nations Cup ×4'],
    rivals: ['JPN'], qualification: 'AFC — group winners',
    manager: { name: 'Tony Popovic', since: 2024, nationality: 'Australia' },
    captain: 'Mathew Ryan', homeStadium: 'Stadium Australia, Sydney', formation: '4-2-3-1',
    funFact: 'Australia switched from the Oceania confederation to Asia in 2006, significantly boosting their WC qualification chances.',
    funFacts: [
      'Australia moved from Oceania to the Asian confederation in 2006 to face tougher qualifying.',
      'They won the AFC Asian Cup on home soil in 2015.',
      'The Socceroos reached the Round of 16 at the 2022 World Cup, their best showing in 16 years.',
    ],
    players: [
      { name: 'Mathew Ryan',     pos: 'GK', club: 'Real Sociedad', age: 33, number: 1,  caps: 90, goals: 0, isCaptain: true, isStar: true },
      { name: 'Harry Souttar',   pos: 'DF', club: 'Leicester',     age: 26, number: 19, caps: 30, goals: 5 },
      { name: 'Aaron Mooy',      pos: 'MF', club: 'Celtic',        age: 35, number: 13, caps: 57, goals: 7 },
      { name: 'Ajdin Hrustic',   pos: 'MF', club: 'Hellas Verona', age: 29, number: 22, caps: 30, goals: 3 },
      { name: 'Mathew Leckie',   pos: 'FW', club: 'Melbourne City', age: 34, number: 7,  caps: 80, goals: 14, isStar: true },
      { name: 'Garang Kuol',     pos: 'FW', club: 'Hearts',        age: 22, number: 23, caps: 15, goals: 2 },
    ],
  },
  IRN: {
    nickname: 'Team Melli', confederation: 'AFC', language: 'Persian',
    colors: { primary: '#239F40', secondary: '#DA0000' },
    capital: 'Tehran', population: '87M', continent: 'Asia',
    fifaRanking: 22, fifaRankingPrev: 20, wcAppearances: 6, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1978,
    honors: ['AFC Asian Cup ×3 (1968, 1972, 1976)'],
    rivals: ['KSA', 'IRQ'], qualification: 'AFC — group winners',
    manager: { name: 'Amir Ghalenoei', since: 2023, nationality: 'Iran' },
    captain: 'Alireza Jahanbakhsh', homeStadium: 'Azadi Stadium, Tehran', formation: '4-3-3',
    funFact: 'Iran\'s 2022 team stood defiantly silent during the anthem in solidarity with protesters back home.',
    funFacts: [
      'Iran are among Asia\'s strongest sides, frequently topping the continental rankings.',
      'They won three consecutive AFC Asian Cups between 1968 and 1976.',
      'Iran beat Wales in dramatic fashion with two stoppage-time goals at the 2022 World Cup.',
    ],
    players: [
      { name: 'Alireza Beiranvand',pos:'GK',club: 'Persepolis',      age: 32, number: 1,  caps: 75, goals: 0 },
      { name: 'Milad Mohammadi',pos: 'DF', club: 'AEK Athens',       age: 30, number: 5,  caps: 55, goals: 1 },
      { name: 'Saman Ghoddos',  pos: 'MF', club: 'Brentford',        age: 31, number: 21, caps: 45, goals: 6 },
      { name: 'Mehdi Taremi',    pos: 'FW', club: 'Inter Milan',      age: 32, number: 9,  caps: 90, goals: 50, isCaptain: true, isStar: true },
      { name: 'Sardar Azmoun',   pos: 'FW', club: 'Bayer Leverkusen', age: 30, number: 20, caps: 80, goals: 45, isStar: true },
      { name: 'Ali Gholizadeh', pos: 'FW', club: 'Sharjah',          age: 29, number: 17, caps: 40, goals: 7 },
    ],
  },
  KSA: {
    nickname: 'Green Falcons', confederation: 'AFC', language: 'Arabic',
    colors: { primary: '#006C35', secondary: '#FFFFFF' },
    capital: 'Riyadh', population: '35M', continent: 'Asia',
    fifaRanking: 55, fifaRankingPrev: 56, wcAppearances: 6, bestResult: 'Round of 16 (1994)',
    titles: [], firstAppearance: 1994,
    honors: ['AFC Asian Cup ×3 (1984, 1988, 1996)'],
    rivals: ['IRN', 'IRQ'], qualification: 'AFC — group winners',
    manager: { name: 'Hervé Renard', since: 2023, nationality: 'France' },
    captain: 'Salem Al-Dawsari', homeStadium: 'King Fahd Stadium, Riyadh', formation: '4-2-3-1',
    funFact: 'Saudi Arabia pulled off one of the biggest World Cup upsets ever, beating Argentina 2-1 at Qatar 2022.',
    funFacts: [
      'Saudi Arabia shocked eventual champions Argentina 2-1 in the 2022 group stage.',
      'On their World Cup debut in 1994 they reached the Round of 16.',
      'The Green Falcons have won the Asian Cup three times.',
    ],
    players: [
      { name: 'Mohammed Al-Owais',pos: 'GK', club: 'Al Hilal',      age: 33, number: 21, caps: 60, goals: 0 },
      { name: 'Ali Al-Bulaihi',  pos: 'DF', club: 'Al Hilal',       age: 33, number: 5,  caps: 55, goals: 2 },
      { name: 'Ali Al-Hassan',   pos: 'MF', club: 'Al Shabab',      age: 26, number: 14, caps: 30, goals: 2 },
      { name: 'Salem Al-Dawsari', pos: 'FW', club: 'Al Hilal',      age: 33, number: 10, caps: 85, goals: 22, isCaptain: true, isStar: true },
      { name: 'Firas Al-Buraikan',pos: 'FW', club: 'Al Fateh',      age: 25, number: 9,  caps: 40, goals: 12, isStar: true },
      { name: 'Saleh Al-Shehri', pos: 'FW', club: 'Al Hilal',       age: 32, number: 11, caps: 45, goals: 14 },
    ],
  },
  IRQ: {
    nickname: 'Lions of Mesopotamia', confederation: 'AFC', language: 'Arabic',
    colors: { primary: '#007A3D', secondary: '#FFFFFF' },
    capital: 'Baghdad', population: '42M', continent: 'Asia',
    fifaRanking: 70, fifaRankingPrev: 75, wcAppearances: 1, bestResult: 'Group Stage (1986)',
    titles: [], firstAppearance: 1986,
    honors: ['AFC Asian Cup (2007)'],
    rivals: ['IRN', 'KSA'], qualification: 'AFC — playoff',
    manager: { name: 'Graham Arnold', since: 2025, nationality: 'Australia' },
    captain: 'Jalal Hassan', homeStadium: 'Basra International Stadium', formation: '4-2-3-1',
    funFact: 'Iraq won the AFC Asian Cup in 2007, their first and only continental title, defeating Saudi Arabia in the final.',
    funFacts: [
      'Iraq won the 2007 Asian Cup amid extraordinary hardship at home — a unifying national triumph.',
      'Their only previous World Cup appearance came in 1986.',
      'The Lions of Mesopotamia often play "home" games abroad due to security restrictions.',
    ],
    players: [
      { name: 'Jalal Hassan',    pos: 'GK', club: 'Al Zawraa',      age: 31, number: 1,  caps: 40, goals: 0, isCaptain: true },
      { name: 'Rebin Sulaka',    pos: 'DF', club: 'Al Zawraa',      age: 28, number: 3,  caps: 35, goals: 2 },
      { name: 'Amjad Attwan',    pos: 'MF', club: 'Al Shorta',      age: 29, number: 8,  caps: 45, goals: 5 },
      { name: 'Ali Faez',        pos: 'MF', club: 'Duhok SC',       age: 26, number: 6,  caps: 40, goals: 3 },
      { name: 'Mohanad Ali',     pos: 'FW', club: 'Al Zawraa',      age: 27, number: 10, caps: 50, goals: 18, isStar: true },
      { name: 'Aymen Hussein',   pos: 'FW', club: 'Al Shorta',      age: 28, number: 9,  caps: 55, goals: 22, isStar: true },
    ],
  },
  QAT: {
    nickname: 'The Maroon', confederation: 'AFC', language: 'Arabic',
    colors: { primary: '#8A1538', secondary: '#FFFFFF' },
    capital: 'Doha', population: '2.9M', continent: 'Asia',
    fifaRanking: 58, fifaRankingPrev: 35, wcAppearances: 2, bestResult: 'Group Stage (2022 host)',
    titles: [], firstAppearance: 2022,
    honors: ['AFC Asian Cup ×2 (2019, 2023)'],
    rivals: ['KSA', 'UAE'], qualification: 'AFC — group winners',
    manager: { name: 'Julen Lopetegui', since: 2025, nationality: 'Spain' },
    captain: 'Hassan Al-Haydos', homeStadium: 'Lusail Stadium, Doha', formation: '3-5-2',
    funFact: 'Qatar hosted the 2022 World Cup, the first in the Middle East, and became the first host nation to be eliminated in the group stage.',
    funFacts: [
      'Qatar hosted the first Middle Eastern World Cup in 2022.',
      'They are back-to-back AFC Asian Cup champions (2019 and 2023).',
      'Akram Afif was named MVP of the 2023 Asian Cup, scoring a hat-trick of penalties in the final.',
    ],
    players: [
      { name: 'Meshaal Barsham', pos: 'GK', club: 'Al Sadd',        age: 28, number: 22, caps: 45, goals: 0 },
      { name: 'Bassam Al-Rawi',  pos: 'DF', club: 'Al Sadd',        age: 29, number: 2,  caps: 60, goals: 4 },
      { name: 'Hassan Al-Haydos',pos: 'MF', club: 'Al Sadd',        age: 34, number: 10, caps: 175, goals: 35, isCaptain: true },
      { name: 'Assim Madibo',    pos: 'MF', club: 'Al Sadd',        age: 27, number: 12, caps: 50, goals: 1 },
      { name: 'Akram Afif',      pos: 'FW', club: 'Al Sadd',        age: 28, number: 11, caps: 110, goals: 35, isStar: true },
      { name: 'Almoez Ali',      pos: 'FW', club: 'Al Duhail',      age: 28, number: 19, caps: 95, goals: 45, isStar: true },
    ],
  },
  USA: {
    nickname: 'The Stars and Stripes', confederation: 'CONCACAF', language: 'English',
    colors: { primary: '#0A3161', secondary: '#B31942' },
    capital: 'Washington D.C.', population: '335M', continent: 'North America',
    fifaRanking: 16, fifaRankingPrev: 16, wcAppearances: 11, bestResult: '3rd Place (1930)',
    titles: [], firstAppearance: 1930,
    honors: ['CONCACAF Gold Cup ×7', 'CONCACAF Nations League ×3'],
    rivals: ['MEX', 'CAN'], qualification: 'Co-host — qualified automatically',
    manager: { name: 'Mauricio Pochettino', since: 2024, nationality: 'Argentina' },
    captain: 'Christian Pulisic', homeStadium: 'Rotating (co-host 2026)', formation: '4-3-3',
    funFact: 'The USA co-hosts 2026 alongside Canada and Mexico, aiming to improve on their best result since 1930.',
    funFacts: [
      'The USA finished 3rd at the very first World Cup in 1930 — still their best result.',
      'They co-host the 2026 tournament with Mexico and Canada.',
      'Christian Pulisic became the most expensive American player ever when he joined Chelsea in 2019.',
    ],
    players: [
      { name: 'Matt Turner',      pos: 'GK', club: 'Crystal Palace', age: 30, number: 1,  caps: 45, goals: 0 },
      { name: 'Weston McKennie', pos: 'MF', club: 'Leeds',           age: 27, number: 8,  caps: 55, goals: 11 },
      { name: 'Yunus Musah',      pos: 'MF', club: 'AC Milan',       age: 23, number: 6,  caps: 40, goals: 0 },
      { name: 'Giovanni Reyna',   pos: 'MF', club: 'Dortmund',       age: 23, number: 7,  caps: 30, goals: 5 },
      { name: 'Christian Pulisic',pos: 'FW', club: 'AC Milan',       age: 27, number: 10, caps: 75, goals: 30, isCaptain: true, isStar: true },
      { name: 'Tim Weah',         pos: 'FW', club: 'Juventus',       age: 25, number: 21, caps: 45, goals: 6, isStar: true },
    ],
  },
  MEX: {
    // ── identity ──
    nickname: 'El Tri',
    confederation: 'CONCACAF',
    colors: { primary: '#006847', secondary: '#CE1126' },
    language: 'Spanish',
    // ── demographics ──
    capital: 'Mexico City', population: '130M', continent: 'North America',
    // ── history ──
    fifaRanking: 15, fifaRankingPrev: 17, wcAppearances: 17,
    bestResult: 'Quarter-finals (1970, 1986)',
    titles: [],
    firstAppearance: 1930,
    honors: ['CONCACAF Gold Cup × 9', 'Confederations Cup (1999)', 'Olympic Gold (2012)'],
    rivals: ['USA', 'CRC'],
    // ── tournament 2026 ──
    qualification: 'Co-host — qualified automatically',
    manager: { name: 'Javier Aguirre', since: 2024, nationality: 'Mexico' },
    captain: 'Edson Álvarez',
    homeStadium: 'Estadio Azteca, Mexico City',
    formation: '4-3-3',
    // ── editorial ──
    funFact: 'Mexico has famously reached the Round of 16 in seven consecutive World Cups (1994-2018), known as the "Quinto Partido" curse.',
    funFacts: [
      'Mexico has reached the Round of 16 in seven consecutive World Cups (1994-2018) — but never broken the "Quinto Partido" curse to reach a 5th game.',
      'Estadio Azteca is the only stadium to host two World Cup finals (1970 & 1986) and will become the first to host matches at three World Cups in 2026.',
      'Mexico are the most successful CONCACAF nation, with a record 9 Gold Cup titles.',
    ],
    // ── squad (number/caps/goals are mock placeholders) ──
    players: [
      { name: 'Guillermo Ochoa',  pos: 'GK', club: 'América',         age: 40, number: 13, caps: 151, goals: 0 },
      { name: 'Johan Vásquez',    pos: 'DEF', club: 'Genoa',          age: 27, number: 3,  caps: 38,  goals: 2 },
      { name: 'César Montes',     pos: 'DEF', club: 'Almería',        age: 28, number: 5,  caps: 55,  goals: 5 },
      { name: 'Jorge Sánchez',    pos: 'DEF', club: 'Cruz Azul',      age: 28, number: 19, caps: 41,  goals: 1 },
      { name: 'Edson Álvarez',    pos: 'MF', club: 'West Ham',        age: 27, number: 4,  caps: 82,  goals: 3, isCaptain: true },
      { name: 'Luis Chávez',      pos: 'MF', club: 'Dynamo Moscow',   age: 29, number: 14, caps: 45,  goals: 5 },
      { name: 'Orbelín Pineda',   pos: 'MF', club: 'AEK Athens',      age: 29, number: 10, caps: 60,  goals: 8 },
      { name: 'Hirving Lozano',   pos: 'FW', club: 'San Diego FC',    age: 30, number: 22, caps: 70,  goals: 18, isStar: true },
      { name: 'Santiago Giménez', pos: 'FW', club: 'AC Milan',        age: 24, number: 9,  caps: 33,  goals: 12, isStar: true },
      { name: 'Raúl Jiménez',     pos: 'FW', club: 'Fulham',          age: 34, number: 7,  caps: 105, goals: 40 },
      { name: 'Alexis Vega',      pos: 'FW', club: 'Toluca',          age: 28, number: 11, caps: 35,  goals: 6 },
    ],
  },
  CAN: {
    nickname: 'Les Rouges', confederation: 'CONCACAF', language: 'English / French',
    colors: { primary: '#FF0000', secondary: '#FFFFFF' },
    capital: 'Ottawa', population: '38M', continent: 'North America',
    fifaRanking: 44, fifaRankingPrev: 48, wcAppearances: 3, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1986,
    honors: ['CONCACAF Gold Cup (2000)'],
    rivals: ['USA', 'MEX'], qualification: 'Co-host — qualified automatically',
    manager: { name: 'Jesse Marsch', since: 2024, nationality: 'USA' },
    captain: 'Alphonso Davies', homeStadium: 'BMO Field, Toronto', formation: '4-3-3',
    funFact: 'Canada qualified for the 2022 World Cup for the first time since 1986, led by Alphonso Davies and Jonathan David.',
    funFacts: [
      'Canada returned to the World Cup in 2022 after a 36-year absence.',
      'They co-host the 2026 tournament alongside the USA and Mexico.',
      'Alphonso Davies went from playing youth football in Edmonton to winning the Champions League with Bayern.',
    ],
    players: [
      { name: 'Maxime Crépeau',   pos: 'GK', club: 'LA Galaxy',      age: 30, number: 16, caps: 30, goals: 0 },
      { name: 'Alphonso Davies',  pos: 'DF', club: 'Bayern Munich',  age: 25, number: 19, caps: 55, goals: 14, isCaptain: true, isStar: true },
      { name: 'Stephen Eustáquio',pos: 'MF', club: 'Porto',          age: 27, number: 7,  caps: 45, goals: 3 },
      { name: 'Ismaël Koné',      pos: 'MF', club: 'Watford',        age: 23, number: 8,  caps: 35, goals: 2 },
      { name: 'Jonathan David',   pos: 'FW', club: 'LOSC Lille',     age: 25, number: 20, caps: 60, goals: 30, isStar: true },
      { name: 'Tajon Buchanan',   pos: 'FW', club: 'Inter Milan',    age: 26, number: 11, caps: 45, goals: 6 },
    ],
  },
  CRC: {
    capital: 'San José', population: '5.2M', continent: 'North America',
    fifaRanking: 53, wcAppearances: 6, bestResult: 'Quarter-finals (2014)',
    funFact: 'Costa Rica\'s remarkable quarter-final run at Brazil 2014 included eliminating Uruguay and Italy in the group stage.',
    players: [
      { name: 'Keylor Navas',   pos: 'GK', club: 'Newell\'s Old Boys',age: 39 },
      { name: 'Bryan Ruiz',     pos: 'MF', club: 'Retired',          age: 39 },
      { name: 'Joel Campbell',  pos: 'FW', club: 'León',             age: 33 },
      { name: 'Yeltsin Tejeda', pos: 'MF', club: 'CD Saprissa',     age: 32 },
      { name: 'Francisco Calvo',pos: 'DF', club: 'Konyaspor',       age: 31 },
      { name: 'Aarón Suárez',   pos: 'GK', club: 'CD Saprissa',    age: 27 },
    ],
  },
  PAN: {
    nickname: 'La Marea Roja', confederation: 'CONCACAF', language: 'Spanish',
    colors: { primary: '#DA121A', secondary: '#072357' },
    capital: 'Panama City', population: '4.3M', continent: 'North America',
    fifaRanking: 72, fifaRankingPrev: 76, wcAppearances: 2, bestResult: 'Group Stage (2018)',
    titles: [], firstAppearance: 2018,
    honors: ['CONCACAF Nations League Runners-up (2023)'],
    rivals: ['CRC'], qualification: 'CONCACAF — qualified',
    manager: { name: 'Thomas Christiansen', since: 2020, nationality: 'Denmark' },
    captain: 'Aníbal Godoy', homeStadium: 'Estadio Rommel Fernández, Panama City', formation: '4-4-2',
    funFact: 'Panama qualified for their first-ever World Cup in 2018, with the entire nation celebrating in the streets.',
    funFacts: [
      'Panama reached their first-ever World Cup in 2018, triggering a national holiday.',
      'Their qualification goal against Costa Rica is one of the most replayed moments in the nation\'s history.',
      'La Marea Roja have become a rising force in CONCACAF over the past decade.',
    ],
    players: [
      { name: 'Luis Mejía',      pos: 'GK', club: 'Montpellier',    age: 26, number: 1,  caps: 40, goals: 0 },
      { name: 'Eric Davis',      pos: 'DF', club: 'CD Lugo',         age: 36, number: 15, caps: 90, goals: 6 },
      { name: 'Adalberto Carrasquilla',pos:'MF',club:'Al-Qadisiyah', age: 25, number: 6,  caps: 45, goals: 4 },
      { name: 'Aníbal Godoy',    pos: 'MF', club: 'San Jose EQ',     age: 37, number: 20, caps: 145, goals: 5, isCaptain: true },
      { name: 'Ismael Díaz',     pos: 'FW', club: 'Porto',           age: 25, number: 19, caps: 35, goals: 12, isStar: true },
      { name: 'Cecilio Waterman',pos: 'FW', club: 'Konyaspor',       age: 34, number: 9,  caps: 40, goals: 10, isStar: true },
    ],
  },
  HON: {
    capital: 'Tegucigalpa', population: '10M', continent: 'North America',
    fifaRanking: 85, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Honduras appeared at three consecutive World Cups (1982, 2010, 2014) despite never qualifying before or since.',
    players: [
      { name: 'Alberth Elis',    pos: 'FW', club: 'Montpellier',    age: 28 },
      { name: 'Romell Quioto',   pos: 'FW', club: 'CF Montréal',    age: 33 },
      { name: 'Bryan Acosta',    pos: 'MF', club: 'FC Dallas',       age: 31 },
      { name: 'Kervin Arriaga',  pos: 'MF', club: 'Santos Laguna',  age: 24 },
      { name: 'Marcelo Santos',  pos: 'DF', club: 'Marathon',        age: 25 },
      { name: 'Harold Fonseca',  pos: 'GK', club: 'Olimpia',        age: 27 },
    ],
  },
  SLV: {
    capital: 'San Salvador', population: '6.5M', continent: 'North America',
    fifaRanking: 78, wcAppearances: 2, bestResult: 'Group Stage (1970, 1982)',
    funFact: 'El Salvador qualified in 1970 after winning the "Football War" qualifier against Honduras, which sparked a real 100-hour military conflict.',
    players: [
      { name: 'Nelson Bonilla',   pos: 'FW', club: 'ATL Alashkert',  age: 32 },
      { name: 'Enrico Dueñas',   pos: 'FW', club: 'Al Taqdom',      age: 23 },
      { name: 'Darwin Cerén',    pos: 'MF', club: 'Philadelphia Union',age:32},
      { name: 'Joshua Pérez',    pos: 'MF', club: 'Rayo Vallecano', age: 23 },
      { name: 'Roberto Domínguez',pos:'DF', club: 'CD FAS',          age: 27 },
      { name: 'Mario González',  pos: 'GK', club: 'Alianza FC',     age: 27 },
    ],
  },
  JAM: {
    capital: 'Kingston', population: '2.9M', continent: 'North America',
    fifaRanking: 47, wcAppearances: 1, bestResult: 'Group Stage (1998)',
    funFact: 'Jamaica\'s "Reggae Boyz" made their World Cup debut in France 1998 and became cult heroes, starring in a feature film.',
    players: [
      { name: 'Michail Antonio',pos: 'FW', club: 'Nottm Forest',   age: 35 },
      { name: 'Bobby Reid',     pos: 'FW', club: 'Fulham',         age: 31 },
      { name: 'Demarai Gray',   pos: 'FW', club: 'Fulham',         age: 29 },
      { name: 'Andre Blake',    pos: 'GK', club: 'Philadelphia',   age: 33 },
      { name: 'Oniel Fisher',   pos: 'DF', club: 'DC United',      age: 30 },
      { name: 'Ethan Pinnock',  pos: 'DF', club: 'Brentford',      age: 31 },
    ],
  },
  COL: {
    nickname: 'Los Cafeteros', confederation: 'CONMEBOL', language: 'Spanish',
    colors: { primary: '#FCD116', secondary: '#003893' },
    capital: 'Bogotá', population: '52M', continent: 'South America',
    fifaRanking: 12, fifaRankingPrev: 14, wcAppearances: 6, bestResult: 'Quarter-finals (2014)',
    titles: [], firstAppearance: 1962,
    honors: ['Copa América (2001)', 'Copa América Runners-up (2024)'],
    rivals: ['ARG', 'BRA'], qualification: 'CONMEBOL — qualified',
    manager: { name: 'Néstor Lorenzo', since: 2022, nationality: 'Argentina' },
    captain: 'James Rodríguez', homeStadium: 'Estadio Metropolitano, Barranquilla', formation: '4-2-3-1',
    funFact: 'Colombia\'s James Rodríguez won the Golden Boot at the 2014 World Cup and his team reached the quarter-finals for the first time.',
    funFacts: [
      'James Rodríguez won the 2014 World Cup Golden Boot, scoring one of the tournament\'s greatest goals vs Uruguay.',
      'Colombia went on a 28-game unbeaten run before the 2024 Copa América final.',
      'Los Cafeteros won their lone Copa América at home in 2001 without conceding a goal.',
    ],
    players: [
      { name: 'Camilo Vargas',   pos: 'GK', club: 'Atlas FC',        age: 32, number: 1,  caps: 35, goals: 0 },
      { name: 'Dávinson Sánchez',pos: 'DF', club: 'Galatasaray',    age: 28, number: 23, caps: 60, goals: 3 },
      { name: 'James Rodríguez', pos: 'MF', club: 'Rayo Vallecano', age: 33, number: 10, caps: 110, goals: 30, isCaptain: true, isStar: true },
      { name: 'Richard Ríos',    pos: 'MF', club: 'Palmeiras',       age: 25, number: 15, caps: 25, goals: 2 },
      { name: 'Luis Díaz',       pos: 'FW', club: 'Liverpool',       age: 28, number: 7,  caps: 60, goals: 18, isStar: true },
      { name: 'Jhon Córdoba',    pos: 'FW', club: 'Krasnodar',       age: 31, number: 9,  caps: 30, goals: 8 },
    ],
  },
  ECU: {
    nickname: 'La Tri', confederation: 'CONMEBOL', language: 'Spanish',
    colors: { primary: '#FFD100', secondary: '#0072CE' },
    capital: 'Quito', population: '18M', continent: 'South America',
    fifaRanking: 33, fifaRankingPrev: 31, wcAppearances: 4, bestResult: 'Round of 16 (2006)',
    titles: [], firstAppearance: 2002,
    honors: ['World Cup Round of 16 (2006)'],
    rivals: ['PER', 'COL'], qualification: 'CONMEBOL — qualified',
    manager: { name: 'Sebastián Beccacece', since: 2024, nationality: 'Argentina' },
    captain: 'Enner Valencia', homeStadium: 'Estadio Rodrigo Paz Delgado, Quito', formation: '4-3-3',
    funFact: 'Ecuador opened the 2022 World Cup with a 2-0 win over host Qatar, with Enner Valencia scoring both goals.',
    funFacts: [
      'Ecuador opened the 2022 World Cup by beating hosts Qatar 2-0.',
      'Their altitude home in Quito (2,800m) is one of the toughest places to play in world football.',
      'Moisés Caicedo became the most expensive British-record signing when he joined Chelsea in 2023.',
    ],
    players: [
      { name: 'Hernán Galíndez', pos: 'GK', club: 'Aucas',          age: 35, number: 1,  caps: 35, goals: 0 },
      { name: 'Piero Hincapié',  pos: 'DF', club: 'Bayer Leverkusen',age: 23, number: 3,  caps: 40, goals: 2, isStar: true },
      { name: 'Moisés Caicedo',  pos: 'MF', club: 'Chelsea',         age: 23, number: 23, caps: 45, goals: 4, isStar: true },
      { name: 'Gonzalo Plata',   pos: 'FW', club: 'Al Qadsiah',      age: 24, number: 19, caps: 40, goals: 7 },
      { name: 'Enner Valencia',  pos: 'FW', club: 'Internacional',   age: 35, number: 13, caps: 90, goals: 45, isCaptain: true, isStar: true },
      { name: 'Jeremy Sarmiento',pos: 'FW', club: 'Brighton',        age: 23, number: 16, caps: 25, goals: 2 },
    ],
  },
  VEN: {
    capital: 'Caracas', population: '28M', continent: 'South America',
    fifaRanking: 54, wcAppearances: 0, bestResult: '(First World Cup appearance)',
    funFact: 'Venezuela would make history as the only CONMEBOL nation never to have appeared at a World Cup, until qualifying for 2026.',
    players: [
      { name: 'Josef Martínez',  pos: 'FW', club: 'Atlanta United',  age: 31 },
      { name: 'Yeferson Soteldo',pos: 'FW', club: 'Santos',          age: 28 },
      { name: 'Rómulo Otero',    pos: 'MF', club: 'Athletico PR',   age: 32 },
      { name: 'Jefferson Savarino',pos:'FW',club: 'Real Salt Lake',  age: 28 },
      { name: 'Yangel Herrera',  pos: 'MF', club: 'Girona',          age: 26 },
      { name: 'Rafael Romo',     pos: 'GK', club: 'CD Lugo',         age: 35 },
    ],
  },
  BOL: {
    capital: 'Sucre / La Paz', population: '12M', continent: 'South America',
    fifaRanking: 88, wcAppearances: 3, bestResult: 'Group Stage',
    funFact: 'Bolivia plays home games at the Estadio Hernando Siles in La Paz, at 3,637 meters above sea level — the highest major stadium in the world.',
    players: [
      { name: 'Marcelo Moreno',  pos: 'FW', club: 'Cruzeiro',        age: 37 },
      { name: 'Ramiro Vaca',     pos: 'MF', club: 'The Strongest',   age: 33 },
      { name: 'Roberto Fernández',pos:'MF', club: 'Wilstermann',     age: 29 },
      { name: 'Jairo Quinteros', pos: 'DF', club: 'The Strongest',   age: 29 },
      { name: 'Luciano Ursino',  pos: 'MF', club: 'The Strongest',   age: 27 },
      { name: 'Gustavo Viscarra',pos: 'GK', club: 'Bolívar',         age: 33 },
    ],
  },
  URU: {
    nickname: 'La Celeste', confederation: 'CONMEBOL', language: 'Spanish',
    colors: { primary: '#5CBFEB', secondary: '#FFFFFF' },
    capital: 'Montevideo', population: '3.5M', continent: 'South America',
    fifaRanking: 20, fifaRankingPrev: 15, wcAppearances: 14, bestResult: 'Champions (1930, 1950)',
    titles: ['1930', '1950'], firstAppearance: 1930,
    honors: ['World Cup ×2 (1930, 1950)', 'Copa América ×15 (record)', 'Olympic Gold ×2'],
    rivals: ['ARG', 'BRA'], qualification: 'CONMEBOL — qualified',
    manager: { name: 'Marcelo Bielsa', since: 2023, nationality: 'Argentina' },
    captain: 'Federico Valverde', homeStadium: 'Estadio Centenario, Montevideo', formation: '4-3-3',
    funFact: 'Uruguay are two-time World Champions despite having a smaller population than most mid-sized cities.',
    funFacts: [
      'Uruguay won the first-ever World Cup in 1930 on home soil — and famously the 1950 final in the "Maracanazo".',
      'With 15 Copa América titles they share the all-time record with Argentina.',
      'The Estadio Centenario was the venue for the very first World Cup final.',
    ],
    players: [
      { name: 'Sergio Rochet',   pos: 'GK', club: 'Nacional',        age: 30, number: 23, caps: 35, goals: 0 },
      { name: 'Rodrigo Bentancur',pos:'MF', club: 'Tottenham',       age: 27, number: 6,  caps: 60, goals: 4 },
      { name: 'Federico Valverde',pos:'MF', club: 'Real Madrid',     age: 26, number: 15, caps: 70, goals: 12, isCaptain: true, isStar: true },
      { name: 'Giorgian De Arrascaeta',pos:'MF',club:'Flamengo',     age: 30, number: 10, caps: 65, goals: 15 },
      { name: 'Darwin Núñez',    pos: 'FW', club: 'Liverpool',       age: 25, number: 9,  caps: 40, goals: 16, isStar: true },
      { name: 'Facundo Pellistri',pos: 'FW', club: 'Man United',     age: 23, number: 11, caps: 30, goals: 3 },
    ],
  },
  NZL: {
    nickname: 'All Whites', confederation: 'OFC', language: 'English',
    colors: { primary: '#FFFFFF', secondary: '#000000' },
    capital: 'Wellington', population: '5M', continent: 'Oceania',
    fifaRanking: 96, fifaRankingPrev: 101, wcAppearances: 2, bestResult: 'Group Stage',
    titles: [], firstAppearance: 1982,
    honors: ['OFC Nations Cup ×5'],
    rivals: ['AUS'], qualification: 'OFC — winners',
    manager: { name: 'Darren Bazeley', since: 2024, nationality: 'England' },
    captain: 'Chris Wood', homeStadium: 'Eden Park, Auckland', formation: '3-5-2',
    funFact: 'New Zealand\'s "All Whites" went unbeaten at the 2010 World Cup, drawing all three group games including against defending champions Italy.',
    funFacts: [
      'New Zealand were the only unbeaten team at the 2010 World Cup, yet went out in the group stage.',
      'They dominate Oceania, having won the OFC Nations Cup five times.',
      'Captain Chris Wood is the nation\'s all-time leading goalscorer.',
    ],
    players: [
      { name: 'Oliver Sail',     pos: 'GK', club: 'FC Lugano',       age: 26, number: 1,  caps: 15, goals: 0 },
      { name: 'Liberato Cacace', pos: 'DF', club: 'Empoli',          age: 24, number: 3,  caps: 35, goals: 1 },
      { name: 'Matt Garbett',    pos: 'MF', club: 'RKC Waalwijk',   age: 26, number: 8,  caps: 25, goals: 3 },
      { name: 'Clayton Lewis',   pos: 'MF', club: 'Yokohama F. Marinos',age:28, number: 6,  caps: 30, goals: 2 },
      { name: 'Sarpreet Singh',  pos: 'MF', club: 'FC Zürich',       age: 26, number: 10, caps: 30, goals: 4 },
      { name: 'Chris Wood',      pos: 'FW', club: 'Nottm Forest',    age: 33, number: 9,  caps: 75, goals: 40, isCaptain: true, isStar: true },
    ],
  },
  ALG: {
    nickname: 'Les Fennecs', confederation: 'CAF', language: 'Arabic / French',
    colors: { primary: '#007229', secondary: '#FFFFFF' },
    capital: 'Algiers', population: '44M', continent: 'Africa',
    fifaRanking: 37, fifaRankingPrev: 40, wcAppearances: 4, bestResult: 'Round of 16 (2014)',
    titles: [], firstAppearance: 1982,
    honors: ['Africa Cup of Nations ×2 (1990, 2019)'],
    rivals: ['MAR', 'EGY', 'TUN'], qualification: 'CAF — group winners',
    manager: { name: 'Vladimir Petković', since: 2024, nationality: 'Switzerland' },
    captain: 'Riyad Mahrez', homeStadium: 'Stade du 5 Juillet, Algiers', formation: '4-3-3',
    funFact: 'Algeria famously beat West Germany at the 1982 World Cup, prompting the "Disgrace of Gijón" that changed how final group games are scheduled.',
    funFacts: [
      'Algeria\'s 1982 win over West Germany led FIFA to play final group games simultaneously.',
      'They won the 2019 Africa Cup of Nations led by Riyad Mahrez.',
      'The Desert Foxes reached the 2014 World Cup Round of 16, taking eventual champions Germany to extra time.',
    ],
    players: [
      { name: 'Alexandre Oukidja',pos: 'GK', club: 'Metz',           age: 37, number: 1,  caps: 30, goals: 0 },
      { name: 'Aïssa Mandi',     pos: 'DF', club: 'Lille',           age: 34, number: 2,  caps: 90, goals: 4 },
      { name: 'Ismaël Bennacer', pos: 'MF', club: 'AC Milan',        age: 28, number: 7,  caps: 50, goals: 3, isStar: true },
      { name: 'Nabil Bentaleb',  pos: 'MF', club: 'Lille',           age: 31, number: 6,  caps: 45, goals: 2 },
      { name: 'Riyad Mahrez',    pos: 'FW', club: 'Al Ahli',         age: 35, number: 7,  caps: 95, goals: 35, isCaptain: true, isStar: true },
      { name: 'Mohamed Amoura',  pos: 'FW', club: 'Wolfsburg',       age: 26, number: 11, caps: 30, goals: 12, isStar: true },
    ],
  },
  BIH: {
    nickname: 'Zmajevi', confederation: 'UEFA', language: 'Bosnian',
    colors: { primary: '#002F6C', secondary: '#FFD700' },
    capital: 'Sarajevo', population: '3.2M', continent: 'Europe',
    fifaRanking: 74, fifaRankingPrev: 70, wcAppearances: 1, bestResult: 'Group Stage (2014)',
    titles: [], firstAppearance: 2014,
    honors: ['First WC appearance as independent nation in 2014'],
    rivals: ['SRB', 'CRO'], qualification: 'UEFA — playoff',
    manager: { name: 'Sergej Barbarez', since: 2024, nationality: 'Bosnia & Herzegovina' },
    captain: 'Edin Džeko', homeStadium: 'Bilino Polje, Zenica', formation: '4-2-3-1',
    funFact: 'Bosnia & Herzegovina reached their first major tournament at the 2014 World Cup, with captain Edin Džeko leading the line.',
    funFacts: [
      'Bosnia made their major-tournament debut at the 2014 World Cup.',
      'Edin Džeko is the nation\'s all-time leading scorer by a huge margin.',
      'The "Dragons" are powered by a generation that grew up after the country\'s independence.',
    ],
    players: [
      { name: 'Nikola Vasilj',   pos: 'GK', club: 'St. Pauli',       age: 30, number: 1,  caps: 20, goals: 0 },
      { name: 'Sead Kolašinac',  pos: 'DF', club: 'Atalanta',        age: 32, number: 23, caps: 65, goals: 2 },
      { name: 'Amar Dedić',      pos: 'DF', club: 'Benfica',         age: 23, number: 2,  caps: 25, goals: 1 },
      { name: 'Miralem Pjanić',  pos: 'MF', club: 'Al Wasl',         age: 35, number: 8,  caps: 110, goals: 17, isStar: true },
      { name: 'Edin Džeko',      pos: 'FW', club: 'Fenerbahçe',      age: 39, number: 11, caps: 140, goals: 70, isCaptain: true, isStar: true },
      { name: 'Ermedin Demirović',pos:'FW', club: 'Stuttgart',       age: 27, number: 9,  caps: 30, goals: 7 },
    ],
  },
  COD: {
    nickname: 'Léopards', confederation: 'CAF', language: 'French',
    colors: { primary: '#007FFF', secondary: '#F7D618' },
    capital: 'Kinshasa', population: '99M', continent: 'Africa',
    fifaRanking: 57, fifaRankingPrev: 60, wcAppearances: 1, bestResult: 'Group Stage (1974, as Zaire)',
    titles: [], firstAppearance: 1974,
    honors: ['Africa Cup of Nations ×2 (1968, 1974)'],
    rivals: ['COG'], qualification: 'CAF — group winners',
    manager: { name: 'Sébastien Desabre', since: 2022, nationality: 'France' },
    captain: 'Chancel Mbemba', homeStadium: 'Stade des Martyrs, Kinshasa', formation: '4-3-3',
    funFact: 'DR Congo (then Zaire) was the first Black African nation to reach the World Cup, in 1974.',
    funFacts: [
      'As Zaire, DR Congo became the first Black African nation at a World Cup in 1974.',
      'The Leopards won the Africa Cup of Nations in 1968 and 1974.',
      'They reached the AFCON semi-finals in 2024 after a long resurgence.',
    ],
    players: [
      { name: 'Lionel Mpasi',    pos: 'GK', club: 'Rodez',           age: 30, number: 16, caps: 20, goals: 0 },
      { name: 'Chancel Mbemba',  pos: 'DF', club: 'Lille',           age: 31, number: 4,  caps: 70, goals: 4, isCaptain: true, isStar: true },
      { name: 'Charles Pickel',  pos: 'MF', club: 'Cremonese',       age: 28, number: 6,  caps: 35, goals: 1 },
      { name: 'Cédric Bakambu',  pos: 'FW', club: 'Real Betis',      age: 34, number: 11, caps: 60, goals: 20, isStar: true },
      { name: 'Yoane Wissa',     pos: 'FW', club: 'Newcastle',       age: 29, number: 9,  caps: 30, goals: 9, isStar: true },
      { name: 'Silas Katompa',   pos: 'FW', club: 'Stuttgart',       age: 27, number: 10, caps: 25, goals: 5 },
    ],
  },
  CPV: {
    nickname: 'Tubarões Azuis', confederation: 'CAF', language: 'Portuguese / Creole',
    colors: { primary: '#003893', secondary: '#FFFFFF' },
    capital: 'Praia', population: '0.6M', continent: 'Africa',
    fifaRanking: 70, fifaRankingPrev: 73, wcAppearances: 0, bestResult: 'Debut (2026)',
    titles: [], firstAppearance: 2026,
    honors: ['First-ever World Cup qualification (2026)'],
    rivals: ['SEN'], qualification: 'CAF — group winners (first-ever)',
    manager: { name: 'Bubista', since: 2020, nationality: 'Cape Verde' },
    captain: 'Ryan Mendes', homeStadium: 'Estádio Nacional, Praia', formation: '4-3-3',
    funFact: 'With around 525,000 people, Cape Verde will be the smallest nation by population ever to play at a World Cup.',
    funFacts: [
      'Cape Verde qualified for their first-ever World Cup in 2026.',
      'They are the second-smallest nation by population to ever qualify, behind Iceland.',
      'The Blue Sharks pulled off historic wins over much larger African nations on the road to 2026.',
    ],
    players: [
      { name: 'Vozinha',         pos: 'GK', club: 'AVS',             age: 35, number: 1,  caps: 40, goals: 0 },
      { name: 'Roberto Lopes',   pos: 'DF', club: 'Shamrock Rovers', age: 33, number: 5,  caps: 50, goals: 3 },
      { name: 'Kenny Rocha Santos',pos:'MF',club: 'Hapoel Be\'er Sheva',age: 29, number: 8, caps: 30, goals: 2 },
      { name: 'Ryan Mendes',     pos: 'FW', club: 'Al Tai',          age: 35, number: 10, caps: 65, goals: 18, isCaptain: true, isStar: true },
      { name: 'Garry Rodrigues', pos: 'FW', club: 'PAOK',            age: 35, number: 7,  caps: 40, goals: 10, isStar: true },
      { name: 'Bebé',            pos: 'FW', club: 'Rayo Vallecano',  age: 35, number: 11, caps: 30, goals: 6 },
    ],
  },
  CUW: {
    nickname: 'Famia Kòrsou', confederation: 'CONCACAF', language: 'Dutch / Papiamento',
    colors: { primary: '#002B7F', secondary: '#F9E814' },
    capital: 'Willemstad', population: '0.15M', continent: 'North America',
    fifaRanking: 82, fifaRankingPrev: 90, wcAppearances: 0, bestResult: 'Debut (2026)',
    titles: [], firstAppearance: 2026,
    honors: ['Caribbean Cup (2017)', 'First-ever World Cup qualification (2026)'],
    rivals: [], qualification: 'CONCACAF — qualified (first-ever)',
    manager: { name: 'Dick Advocaat', since: 2024, nationality: 'Netherlands' },
    captain: 'Leandro Bacuna', homeStadium: 'Ergilio Hato Stadium, Willemstad', formation: '4-3-3',
    funFact: 'Curaçao, with around 150,000 people, are set to become the smallest country ever to play at a World Cup.',
    funFacts: [
      'Curaçao would be the smallest nation by both area and population ever to reach a World Cup.',
      'Veteran Dutch coach Dick Advocaat led the islanders to historic qualification.',
      'Many of their players were developed in the Netherlands\' renowned academies.',
    ],
    players: [
      { name: 'Eloy Room',       pos: 'GK', club: 'Columbus Crew',   age: 36, number: 1,  caps: 45, goals: 0 },
      { name: 'Cuco Martina',    pos: 'DF', club: 'Free agent',      age: 36, number: 2,  caps: 40, goals: 1 },
      { name: 'Leandro Bacuna',  pos: 'MF', club: 'Almere City',     age: 34, number: 8,  caps: 45, goals: 7, isCaptain: true },
      { name: 'Juninho Bacuna',  pos: 'MF', club: 'Birmingham City', age: 28, number: 6,  caps: 30, goals: 3 },
      { name: 'Tahith Chong',    pos: 'FW', club: 'Sheffield United',age: 26, number: 10, caps: 20, goals: 4, isStar: true },
      { name: 'Jürgen Locadia',  pos: 'FW', club: 'PEC Zwolle',      age: 32, number: 9,  caps: 25, goals: 8, isStar: true },
    ],
  },
  HAI: {
    nickname: 'Les Grenadiers', confederation: 'CONCACAF', language: 'French / Creole',
    colors: { primary: '#00209F', secondary: '#D21034' },
    capital: 'Port-au-Prince', population: '11.5M', continent: 'North America',
    fifaRanking: 83, fifaRankingPrev: 87, wcAppearances: 1, bestResult: 'Group Stage (1974)',
    titles: [], firstAppearance: 1974,
    honors: ['Caribbean Cup ×1'],
    rivals: [], qualification: 'CONCACAF — qualified',
    manager: { name: 'Sébastien Migné', since: 2023, nationality: 'France' },
    captain: 'Duckens Nazon', homeStadium: 'Stade Sylvio Cator, Port-au-Prince', formation: '4-4-2',
    funFact: 'At the 1974 World Cup, Haiti\'s Emmanuel Sanon ended Italy goalkeeper Dino Zoff\'s record 1,142-minute unbeaten streak.',
    funFacts: [
      'Haiti\'s Emmanuel Sanon famously beat the great Dino Zoff to score at the 1974 World Cup.',
      'They return to the World Cup in 2026 after a 52-year absence.',
      'The Grenadiers have played "home" qualifiers abroad due to instability at home.',
    ],
    players: [
      { name: 'Johny Placide',   pos: 'GK', club: 'Valenciennes',    age: 37, number: 1,  caps: 60, goals: 0 },
      { name: 'Ricardo Adé',     pos: 'DF', club: 'Al-Najma',        age: 35, number: 4,  caps: 45, goals: 3 },
      { name: 'Danley Jean Jacques',pos:'MF',club: 'Reims',          age: 25, number: 8,  caps: 25, goals: 2 },
      { name: 'Duckens Nazon',   pos: 'FW', club: 'Aris Limassol',   age: 31, number: 9,  caps: 60, goals: 22, isCaptain: true, isStar: true },
      { name: 'Frantzdy Pierrot',pos: 'FW', club: 'Çaykur Rizespor', age: 30, number: 11, caps: 35, goals: 14, isStar: true },
      { name: 'Don Deedson',     pos: 'FW', club: 'Boavista',        age: 23, number: 7,  caps: 15, goals: 3 },
    ],
  },
  JOR: {
    nickname: 'Al-Nashama', confederation: 'AFC', language: 'Arabic',
    colors: { primary: '#007A3D', secondary: '#CE1126' },
    capital: 'Amman', population: '11M', continent: 'Asia',
    fifaRanking: 62, fifaRankingPrev: 68, wcAppearances: 0, bestResult: 'Debut (2026)',
    titles: [], firstAppearance: 2026,
    honors: ['AFC Asian Cup Runners-up (2023)', 'First-ever World Cup qualification (2026)'],
    rivals: ['IRQ', 'KSA'], qualification: 'AFC — group winners (first-ever)',
    manager: { name: 'Jamal Sellami', since: 2024, nationality: 'Morocco' },
    captain: 'Mousa Al-Tamari', homeStadium: 'Amman International Stadium', formation: '4-3-3',
    funFact: 'Jordan reached the 2023 Asian Cup final — beating South Korea in the semi — and qualified for their first-ever World Cup in 2026.',
    funFacts: [
      'Jordan reached their first Asian Cup final in 2023, stunning South Korea in the semis.',
      'They qualified for their first-ever World Cup for 2026.',
      'Mousa Al-Tamari became the first Jordanian to score in Europe\'s top leagues regularly.',
    ],
    players: [
      { name: 'Yazeed Abulaila', pos: 'GK', club: 'Al-Faisaly',      age: 30, number: 1,  caps: 30, goals: 0 },
      { name: 'Yazan Al-Arab',   pos: 'DF', club: 'Al-Wehdat',       age: 29, number: 5,  caps: 40, goals: 2 },
      { name: 'Nour Al-Rawabdeh',pos: 'MF', club: 'Al-Hussein',      age: 25, number: 8,  caps: 25, goals: 3 },
      { name: 'Mousa Al-Tamari', pos: 'FW', club: 'Montpellier',     age: 28, number: 7,  caps: 65, goals: 20, isCaptain: true, isStar: true },
      { name: 'Yazan Al-Naimat', pos: 'FW', club: 'Al-Ahli',         age: 26, number: 9,  caps: 45, goals: 14, isStar: true },
      { name: 'Ali Olwan',       pos: 'FW', club: 'Zamalek',         age: 27, number: 11, caps: 40, goals: 12 },
    ],
  },
  NOR: {
    nickname: 'Løvene', confederation: 'UEFA', language: 'Norwegian',
    colors: { primary: '#BA0C2F', secondary: '#00205B' },
    capital: 'Oslo', population: '5.4M', continent: 'Europe',
    fifaRanking: 30, fifaRankingPrev: 33, wcAppearances: 3, bestResult: 'Round of 16 (1998)',
    titles: [], firstAppearance: 1938,
    honors: ['World Cup Round of 16 (1998)'],
    rivals: ['SWE', 'DEN'], qualification: 'UEFA — group winners',
    manager: { name: 'Ståle Solbakken', since: 2020, nationality: 'Norway' },
    captain: 'Martin Ødegaard', homeStadium: 'Ullevaal Stadion, Oslo', formation: '4-3-3',
    funFact: 'Norway return to the World Cup for the first time since 1998, powered by superstar striker Erling Haaland.',
    funFacts: [
      'Norway qualified for their first World Cup since 1998.',
      'They have never lost a World Cup match to Brazil, beating them in both 1998 meetings.',
      'Erling Haaland is among the most prolific goalscorers football has ever seen.',
    ],
    players: [
      { name: 'Ørjan Nyland',    pos: 'GK', club: 'Sevilla',         age: 35, number: 1,  caps: 45, goals: 0 },
      { name: 'Kristoffer Ajer', pos: 'DF', club: 'Brentford',       age: 27, number: 5,  caps: 45, goals: 2 },
      { name: 'Martin Ødegaard', pos: 'MF', club: 'Arsenal',         age: 27, number: 10, caps: 60, goals: 8, isCaptain: true, isStar: true },
      { name: 'Antonio Nusa',    pos: 'FW', club: 'RB Leipzig',      age: 20, number: 20, caps: 25, goals: 5 },
      { name: 'Erling Haaland',  pos: 'FW', club: 'Man City',        age: 25, number: 9,  caps: 45, goals: 45, isStar: true },
      { name: 'Alexander Sørloth',pos:'FW', club: 'Atlético Madrid', age: 30, number: 11, caps: 60, goals: 22, isStar: true },
    ],
  },
  PAR: {
    nickname: 'La Albirroja', confederation: 'CONMEBOL', language: 'Spanish / Guaraní',
    colors: { primary: '#D52B1E', secondary: '#0038A8' },
    capital: 'Asunción', population: '7M', continent: 'South America',
    fifaRanking: 50, fifaRankingPrev: 56, wcAppearances: 8, bestResult: 'Quarter-finals (2010)',
    titles: [], firstAppearance: 1930,
    honors: ['Copa América ×2 (1953, 1979)', 'Olympic Silver (2004)'],
    rivals: ['ARG', 'URU'], qualification: 'CONMEBOL — qualified',
    manager: { name: 'Gustavo Alfaro', since: 2024, nationality: 'Argentina' },
    captain: 'Gustavo Gómez', homeStadium: 'Estadio Defensores del Chaco, Asunción', formation: '4-4-2',
    funFact: 'Paraguay reached the World Cup quarter-finals in 2010, falling 1-0 to eventual champions Spain.',
    funFacts: [
      'Paraguay reached their first World Cup quarter-final in 2010.',
      'Goalkeeper-captain José Luis Chilavert famously scored free-kicks and penalties for the national team.',
      'La Albirroja are renowned for their fierce defensive resilience.',
    ],
    players: [
      { name: 'Roberto Fernández',pos:'GK', club: 'Olympia',         age: 25, number: 1,  caps: 20, goals: 0 },
      { name: 'Gustavo Gómez',   pos: 'DF', club: 'Palmeiras',       age: 32, number: 2,  caps: 65, goals: 8, isCaptain: true, isStar: true },
      { name: 'Andrés Cubas',    pos: 'MF', club: 'Vancouver',       age: 29, number: 5,  caps: 35, goals: 1 },
      { name: 'Damián Bobadilla',pos: 'MF', club: 'San Lorenzo',     age: 22, number: 8,  caps: 20, goals: 2 },
      { name: 'Miguel Almirón',  pos: 'FW', club: 'Atlanta United',  age: 31, number: 10, caps: 65, goals: 12, isStar: true },
      { name: 'Antonio Sanabria',pos: 'FW', club: 'Torino',          age: 29, number: 9,  caps: 55, goals: 15, isStar: true },
    ],
  },
  SWE: {
    nickname: 'Blågult', confederation: 'UEFA', language: 'Swedish',
    colors: { primary: '#FECC00', secondary: '#005293' },
    capital: 'Stockholm', population: '10.5M', continent: 'Europe',
    fifaRanking: 40, fifaRankingPrev: 38, wcAppearances: 12, bestResult: 'Runners-up (1958)',
    titles: [], firstAppearance: 1934,
    honors: ['World Cup Runners-up (1958)', 'Olympic Gold (1948)'],
    rivals: ['DEN', 'NOR'], qualification: 'UEFA — group winners',
    manager: { name: 'Jon Dahl Tomasson', since: 2024, nationality: 'Denmark' },
    captain: 'Victor Lindelöf', homeStadium: 'Friends Arena, Stockholm', formation: '4-3-3',
    funFact: 'Sweden finished runners-up as hosts in 1958 — the World Cup where a 17-year-old Pelé burst onto the scene.',
    funFacts: [
      'Sweden reached the World Cup final on home soil in 1958, losing to Pelé\'s Brazil.',
      'They produced legends from Henrik Larsson to Zlatan Ibrahimović.',
      'A new generation led by Isak and Gyökeres has reignited the Blågult.',
    ],
    players: [
      { name: 'Robin Olsen',     pos: 'GK', club: 'Aston Villa',     age: 36, number: 1,  caps: 70, goals: 0 },
      { name: 'Victor Lindelöf', pos: 'DF', club: 'Aston Villa',     age: 31, number: 3,  caps: 75, goals: 4, isCaptain: true },
      { name: 'Lucas Bergvall',  pos: 'MF', club: 'Tottenham',       age: 19, number: 8,  caps: 15, goals: 2 },
      { name: 'Dejan Kulusevski',pos: 'MF', club: 'Tottenham',       age: 25, number: 10, caps: 45, goals: 7, isStar: true },
      { name: 'Alexander Isak',  pos: 'FW', club: 'Liverpool',       age: 26, number: 11, caps: 50, goals: 16, isStar: true },
      { name: 'Viktor Gyökeres', pos: 'FW', club: 'Arsenal',         age: 27, number: 9,  caps: 30, goals: 13, isStar: true },
    ],
  },
  UZB: {
    nickname: 'White Wolves', confederation: 'AFC', language: 'Uzbek',
    colors: { primary: '#1EB53A', secondary: '#0099B5' },
    capital: 'Tashkent', population: '35M', continent: 'Asia',
    fifaRanking: 57, fifaRankingPrev: 62, wcAppearances: 0, bestResult: 'Debut (2026)',
    titles: [], firstAppearance: 2026,
    honors: ['First-ever World Cup qualification (2026)'],
    rivals: ['IRN', 'KSA'], qualification: 'AFC — group runners-up (first-ever)',
    manager: { name: 'Timur Kapadze', since: 2025, nationality: 'Uzbekistan' },
    captain: 'Eldor Shomurodov', homeStadium: 'Milliy Stadium, Tashkent', formation: '4-2-3-1',
    funFact: 'Uzbekistan qualified for their first-ever World Cup in 2026 after decades of near-misses in Asian qualifying.',
    funFacts: [
      'Uzbekistan reached their first-ever World Cup for 2026.',
      'Defender Abdukodir Khusanov became Manchester City\'s first signing from Central Asia.',
      'The White Wolves have long been one of Asia\'s strongest sides without ever qualifying — until now.',
    ],
    players: [
      { name: 'Utkir Yusupov',   pos: 'GK', club: 'Pakhtakor',       age: 30, number: 1,  caps: 25, goals: 0 },
      { name: 'Abdukodir Khusanov',pos:'DF',club: 'Man City',        age: 21, number: 4,  caps: 25, goals: 1, isStar: true },
      { name: 'Jaloliddin Masharipov',pos:'MF',club:'Pakhtakor',     age: 31, number: 7,  caps: 60, goals: 12 },
      { name: 'Otabek Shukurov', pos: 'MF', club: 'Al-Khaleej',      age: 29, number: 6,  caps: 55, goals: 4 },
      { name: 'Eldor Shomurodov',pos: 'FW', club: 'Roma',            age: 30, number: 9,  caps: 70, goals: 38, isCaptain: true, isStar: true },
      { name: 'Khojiakbar Alijonov',pos:'FW',club: 'Pakhtakor',      age: 26, number: 11, caps: 30, goals: 8 },
    ],
  },
};
